---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: blocky
  namespace: blocky
spec:
  interval: 15m
  chart:
    spec:
      chart: blocky
      version: 18.2.0
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    ## set stopAll to "true" if you do not want to use blocky
    # and/or disable its service
    global:
      stopAll: false
    resources:
      requests:
        cpu: 10m
    service:
      dns:
        externalTrafficPolicy: Local
        loadBalancerIP: ${BLOCKY_IP}
        type: LoadBalancer
        integrations:
          metallb:
            enabled: true
    k8sgateway:
      # -- list of processed domains
      domains:
      - domain: "${DOMAIN_0}"
        dnsChallenge:
          enabled: false
          domain: dns01.clouddns.com
      - domain: "${DOMAIN_1}"
        dnsChallenge:
          enabled: false
          domain: dns01.clouddns.com
      # forward:
      #   enabled: false
      #   primary: tls://1.1.1.1
      #   secondary: tls://1.0.0.1
      #   options:
      #     - name: tls_servername
      #       value: cloudflare-dns.com
    defaultUpstreams:
    - "https://1.1.1.1/dns-query"
    bootstrapDns:
      ips: []
      upstream: "1.1.1.1"    
    queryLog:
      # optional one of: mysql, postgresql, csv, csv-client. If empty, log to console only
      type: "postgresql"

    # configmap:
    #   dashboard:
    #     enabled: false
    #   datasource:
    #     enabled: false

    # cnpg:
    #   main:
    #     enabled: false
