apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:CrFHHe2tr7/AirwWTDg6fkojmgGhRhgXFA/hKfaRmXZ0qzbKv9KEUA==,iv:VTEtqmA2yTgmL0ReQWft8Fq6IGhL03EYi1G6sWquvbY=,tag:8YSn+QZa/kPRIdQPaUC7cA==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1jwlwsx5n7hu79qgpw86g6nuf35c6gauartjpehjgltwgv623aeasst9e8s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwQzAycFRMRTZvRmNxYkdH
            RjVVazVjU0JFNUk4ZGVIUElTdjRacUpDekNBCmxpSHN1Uzd3ZGJpMGZzNFZ3MUY4
            bVVOZFZ1Q2ZGSFUrRERZdWlNbHVabjAKLS0tIHlaRzY4RXFzeXZRVXNPanlrNjIx
            T2JFUWdpb3ZCZDN2MjdjTURORTRCakEK/0Ei8Sz7MoNba7ZnAQ8nOYbET4CGybMJ
            mLTgCbxIbCqcXVBvg5KnVLomy659OXsD2O2E8ZX3zGyWPw2ud8xDFA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-18T14:07:29Z"
    mac: ENC[AES256_GCM,data:Ti2cTNiDKTUURpDGhP3qiE2nZflEud/ik8dETP4SizZOM9Dz2EQXy/Ix3/YdOvnKXnvH50LDaEY23sToI1IY4aI2mEQteL2ce1oC3bCmpOZNIZ/ua7vW1a3ZDDpI0llZzFZ175+wPx0tEm65fg03XVNvXqsSAwooJOHeAVOx0p8=,iv:ifT6mbGkBnrFbm2QAwIc9/tR7EMLw9+UtfKWCoYUxH0=,tag:hWIubaufkXF2L9GaspSuvQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
