apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:cMoaAbL7aQVq0XLSlCin3fggs6aBH9ckWi1bHtI5qf7UjMr8TF+OJw==,iv:CSZu2bOmit8HM+S4Gf9nGm9dkVA9R1WNzDOAXao4QF8=,tag:qmyVfeduawnq671W8JHMcw==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1jwlwsx5n7hu79qgpw86g6nuf35c6gauartjpehjgltwgv623aeasst9e8s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlTzROR0k0a3lqUGI3d0xO
            YWJZQUMzTnJ0TXJVVHB2RUtVRjBwMWt4TUFzCkM2N2VpaksxMGFBSWVFanVPMXJx
            NHhjZUJNejlsYjN5eVlsN3N6L2NLcFEKLS0tIEpFVTBHSG5HOHFJemx3Q3p3NjRy
            NWZjeFgrQUowWjVXVDBQN1JvcGxQZjgKwT8PC6HCFOZSXdlq3S3wzy/2dMCuI/6e
            v/x91pRvVBgH98gl6fu8aEiL+wxWXCuv/r1lfqeuyUETGv6aQsGBzQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-16T18:02:29Z"
    mac: ENC[AES256_GCM,data:dLMuZ+fj2+PfOhBcKBDq+JaG4k6HzHxvv4psUOQ2hGkOwt+nPH4Yf81w0eSCG0uMC6ItSq2BijzDuv9c0gx4IiCiQGg3o6oY0/Vfmh7VDSpcKZlc0KpfSfSB7xfvchZN3tD2oO5ET0ruICRifdAIOzQ04JYIwEiQY+rtMMTufDA=,iv:J8HGQmTx8K86zIc8N1DOUtLHDBddioX1TOEGTIcAuGs=,tag:qu9g5eo4Xx/HVWRsSImLrQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
