apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:6B1G05xAaMMc+TSN3LZyWbYCHdaWm9oxZ0rlFvmO48AGoCVQI8uEVw==,iv:x/3H1CeDNGBUUCM+GlAxOFzVLEtTXn9dEjFbb9sDd6s=,tag:e5R1rZ/a3NfD/GD5LMLh5g==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1jwlwsx5n7hu79qgpw86g6nuf35c6gauartjpehjgltwgv623aeasst9e8s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUeFVGZVkrMWlUaUR1UmJZ
            MjVNTGZGMUFVbDBkd1B2dzQxT3ErWWhHQW5NCmN6MXJudS9acElVaEFMUVdyVFhL
            MU0rRTVDTlFIR2syUGkzckZGRm9DVEEKLS0tIExSMFpvRE5iZlZRZnhleEllbU1p
            TUZEQ0czbEpnVlZoOGh2T0IzSDd4azgKbIic9iY4KCVoDqQKLSBH7xD2CEFuu3Ts
            GftD6a8LhLVzieulbiojR1eRIEK3O8mQcN5z+yBry9k15KuNUyYcvA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-16T19:53:41Z"
    mac: ENC[AES256_GCM,data:GgQVZfxG4RskT1jYcnNxiLcY9plwy1jHe1Ikuau+aUKhty+Jf3UXeokfRghTotkhsmphdWFDEMR+mSqKDsTCe749kzyT2Ir98xulWRr3Bv5SQMhzjOVw7640PwCjqb3QcS4RHTkD1xIAr0D/pZyUG1QpSa4RaB4SS1OweDitVD4=,iv:ccGxAtc9iT8wr/Ak9QKO0fcuTDa4uAvk/nbNKM+tzjY=,tag:UObGHayERzVuaoA5TqoW4Q==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
