apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:rjbuHqByTixODuXglH/Jj1YB6PjX2EM++T0USGPFuPHHTkGWiLkX9w==,iv:ut4TXOUPDGUx1Imn2cS3f9T4FSdeaU9+Iwsu0YPGD60=,tag:M9iFXv7y0bRVPKXFXjYXVA==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1jwlwsx5n7hu79qgpw86g6nuf35c6gauartjpehjgltwgv623aeasst9e8s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzdXdnTndXK3hKa2xZUlVm
            Zjk5VVFIVUN0SGdwZXJFMWxnQnA3RjdJM0JFCkV0MVNIMHR5bTJjR1RpalFqZkg2
            MU9CTnorbExmK09UY0hpY1A5djFGMHMKLS0tIG9BdERsNXlWQWxWTnBtMmZnU085
            dU9aT3llRm96UzJvZjFrSy9lN29NK00Kh0Y21sxgwllfPGr43CPjmccle65SCOOh
            x2jvGFeI1i/4Zv3qhV5g9IBsnLlEv690q8rnDC3OXEW4IgHCaKDscg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-17T22:41:01Z"
    mac: ENC[AES256_GCM,data:agt+jRy8np2do5JPAz+LdPYk3WD9cx5DXiQgWL6EFcAjS6i8v+aEZuE/BjKUS2kNWoCLXT9QLxSqC7vbWtql1GuGqIxnw7oGjYDH3+tYDv8NyLbcgERTq2IjI9BIgjUKUUsrGsyI0aZ7N4q/XCOn8C+DEuI/wSK4hzHoOx9wngY=,iv:n9jxonBI2kj2rGhr3qMZ5dEaLqsHjI8rIz5F5QCbS9E=,tag:Gvy45ExkQwd3Sde4fnOr6Q==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
