apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:qoTEsPKMSxfGQ2iyrex6Qd6Ip09Z/qgVvIPlwlL9wooLhGfnu89IKw==,iv:7Y4zwL1IzBtOoHSvFfGFeV9OqNaeqC5Lmpqv8GD7/9c=,tag:dIknNeBafrnJRzE5hOxVnw==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1jwlwsx5n7hu79qgpw86g6nuf35c6gauartjpehjgltwgv623aeasst9e8s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4NDZ3dzBidUJWVm93dVdr
            N1JlR1c5VTZadW12ajdIZ1FWNE03dUVQVjNFCnVCZlhMNFhwVDJPS3JJRktHbERZ
            WExyZGsvamRmUW1HQ3NhdTBib2NnM00KLS0tIE1tem95S1V6dGNCamJBMCtsQWtw
            UVRTY1d0MWROekhRanVLUkExdytRTjQKrUrL54cJgmiUMH4WrD9X/EQE9ICtw9SG
            ePx2xixWjrShDndCXxlt+CQ/lYt0MzUU1WsAv7Td2Nb7TigIHWiztA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-16T21:42:58Z"
    mac: ENC[AES256_GCM,data:LgSRcsZwk60Wu+7zrhsDWWmSJy7HsVCBo0Zf5WQah1O2j/WMpz5+N0Yxre80o8lsrsOn8hqeXUpqffWJLLQkN0Kp40YxudFXL4uH1hQPdiA/lTQUM8yEW2kqRDsJ1uGt9cOdGpwLHCm8RJYX4km01m+00VmwaIMpYEWn64nmqg8=,iv:wLNTgK19EPoLyQMC9Wm1tjMQGZGVzXdTvHvBLmF8XGg=,tag:uYToXKwszNe1Q5+ZIAWf4w==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
