apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:FOc8va2EnwK8Mi+V93mZAxgrubJhEjPhj8mJUxOd6LIV5XIefuhohg==,iv:Z326YBIX6hzbQMLCOw2t44jDXLr7+QA7iZi5otqwJ6s=,tag:hTIK1EEhkLsLd/1Njitdmw==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1jwlwsx5n7hu79qgpw86g6nuf35c6gauartjpehjgltwgv623aeasst9e8s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaQ2s5U0tHcG1jVU5FS2lO
            aGxTdTFOV2hDQkIxYWo2ejJWWWdIanJTV3hjCnJVVDdFUWZoVjFTNG9mNXRiYTg4
            ay9UQTNhWjJQcTUvZHhHdzVFcXVybzQKLS0tIGs4bGl4cVpyQUlVR3VTT29tYzdx
            TjU1ZnVmREpCTWtJaE82RURGaWxxWU0Kql474Yl3zT80GVGsUmdEEwOjFV1dusYs
            w90SOvB2IMRRVHswmqD1rIfEXkR7EGCmzyFsZNQFMWR1KL2s1G1r4w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-17T23:30:15Z"
    mac: ENC[AES256_GCM,data:t8zw/W1qTG40XNuumrWk5hZbz9PxR6VHIRFy1eDYIT0bL+lI/3GOpMGfdShOfZVHNrilxOdUN6i3dQCXSvfm1hDsPktJdWjuIUGkrhvt+2xqb/blFzOqtjmNY0dXfOKzmTPnB9i8vgJP02yxzaKkGW6WVAUQ4qpEcAqp88wDH78=,iv:5/nuwY9KJB01ztzJt+TEsTGPgWbNloWjgcKa5xhqwTg=,tag:XLZQWDb9fCiGTCqcM07ISg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
