apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:HuEMz03ZazMO5Jb1MCCNRYZgW/1h1RKkyThJGpqxfj46MokJUr7VLA==,iv:vo+e6KqC0M+3xuZMp3meoaey0KuWI03Ezf2ob1le1no=,tag:TYaA9n3jKP7SIE5N1gCfcw==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1jwlwsx5n7hu79qgpw86g6nuf35c6gauartjpehjgltwgv623aeasst9e8s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjbW9mcy93cVhHNmdTRXVq
            S0RLNDFLeEtmc0NEcWZYZTNhMkZlZUdFb1I0CjJJQ0tuNXZISGtyMHgxS1l6VWtl
            N1A5T3R0WWNuYmxUeVB4d2Y0Wjl4aE0KLS0tIDB6aFRlNXp6cnZYWWFCS3VBMHAw
            aHFMUCswalgwcktqTmNFQmdyalNSbkkK36i11+t9zkGeBj4mHQhxsrDkNXhrBHbW
            123vSLPlXmQorqS5OgFVvCt8MpjETodCmHN1Rv6bFvL5uwHuDgd2BQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-13T23:38:13Z"
    mac: ENC[AES256_GCM,data:k/dtVajbi9mUzm/6ldfbaJQzMQTQykOM0fwWitDZYMmdTzpwP7QTXGypg2/kNJjCAIu934n43ugr8Q/MHkYzyTkUT3ZkIvBi69F1zHp6oBm7YTYrg1oDp+1GBy+y1/VhgILLDP9jmIRUXNzTtV+NJEQFbIR4t1lgK4ktT3zn3NM=,iv:aXXAbmylFZqSQVyWVbciIkO5MyPAW6RSvrHkM1i23gY=,tag:Y7VRbkTnyBSzGPywgrKD7w==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
