apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:qHGmGOyfHDfsUucv7AKNPfDG81Q9EGhX+Aq+xKB3az00kDS62cYhBA==,iv:QfZdLiFAOgFSMQoDV1v+CobYrFQXak3sagRxvroBhg4=,tag:VDjVmdsBtOxJizJHrIwXkQ==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1jwlwsx5n7hu79qgpw86g6nuf35c6gauartjpehjgltwgv623aeasst9e8s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDMExqbWVuVXhQYzdwWXox
            SEFOY1ZYUWZlRGJHU2tQSnhIL2NhbGhsRXkwCmdUTldQeklWM090bkZKRThWb2Q3
            UFNMenNmM1VGMGdsTWtrREI1aWgzUUEKLS0tIERHMVpkMS9pN3FTOWVucWQ5V1Ev
            d0IxaU95eUIyYWZGTzduWDMrSURpSzAKvZDT9Vh4hgdD5gqkiq9WncMaovrosH4U
            NJOyCwhd9BuS6C7zdaKxvJVEcdZHjBVDINmWyhu2ZQTFyaGbk6DBJA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-29T23:07:36Z"
    mac: ENC[AES256_GCM,data:FVpgX0r6iYANIePqex0yhYPvhMKdjN4uwqu38RGHchdvmUaLS05L1Y5bTgGadiyCJMGBHwNiKlXGZu8mOGnTDQjoPtz/4627dNkNHB/gfrxqaPUWgLhfpTLEADKWyEm2gdPTN9rMemP2+W9MBLp9SalvrnWNmnXKIDhZXXlhKb0=,iv:uP4DxUwGXiRnHIxIpna3HR5YM6jn2Ow0KzRXkP3UL04=,tag:4xVB3C+gq6RYj6txslULFA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
