apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:hwYxlBGY4ewr/MFNcxb5aA9P7mjNjPD0MeHuJ29Jx2tyR6O7+85m6A==,iv:tyS6EOxN0o8pdOZ5jsvN8oCDAmVi8qjFn00x27ew/x8=,tag:v5yCeI+zd/u0UW9i1mqsYw==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1jwlwsx5n7hu79qgpw86g6nuf35c6gauartjpehjgltwgv623aeasst9e8s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPWnQzcWlsQmxsZG9hN04v
            TEhCb284bjhGaVZFSGU5eXpyeXhHL095VWxZCjBqV2pMQTgvOVExaU9RZUFXdlhV
            ZW1jdEw5NFdRMzIzMTdSaUVRM1ZERXMKLS0tIFQ3bG9rZkRmWlRwMU1NSWloN09z
            LzhsNXJWRnBvSndvd1Qvb1MycGQxRmMKHtBMYkiPssnwHLut56bwSnXnqlv5Vzc8
            XJMcIScds24+nLb4KAwi1uRqAmB9AeedHSPu064/8hVQwwqDeeVBVA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-17T03:38:43Z"
    mac: ENC[AES256_GCM,data:MPcwGS5j3MAtNGfMr7+ElQf/BhJiKgOZfTOnuvWs0WUsNcjMI/4EgCAJ5DZz8A4e7GoptDKEINHQNz//KD0MLTS6LM4UwWkTzdtVLU/1UL1mC3XODfeYuDTgq8tI1EhqzzpIAwxFu9QQfBWztdOSOBFtzL6HCSeR3c6fjhSKNlk=,iv:1I/jB/qeV7bVeJ7RxI1x+uAY1xcLAbxqGyn3JhKyuuo=,tag:L+TzBlgWzbZ9vqvVqJ/15Q==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
