apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:U0CE3TW8yGeOSIM83caFRUMwXgVdXQKdrggbvMH47hJk5aghQEeERA==,iv:IDjB4WhNM/sEdc9cimXztg3Xl7TuP9T0MwjVofCojf8=,tag:euguEcKqZIxvWZKBbg8dOg==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1jwlwsx5n7hu79qgpw86g6nuf35c6gauartjpehjgltwgv623aeasst9e8s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3UXlGUWZhNk5uOUVpLzBB
            ZCtCVHNFSHNWbndNNWkyQ2pDVDhnN0lVN1VNCjN6UElvLzcraVRyNkVlSi9nMGNw
            aE8wb1FnZ1U0clhTUy9XMm00K0JnN2MKLS0tIEtYR0R3d0tqUVZPTXEwaENtK0V4
            UTF4WWlSOFBHcTFWUm1UQTd1MHpXRWMKQAi4TiG/AAh+ki1jX/Le504mPVYiMx04
            BET0NWY7nOSuytRwlMrMiJL24gVNzhq1LBuwpt0zmnTMLyM3cVvYdA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-28T23:24:27Z"
    mac: ENC[AES256_GCM,data:3cqCSyP2YkFBAGnVyddKQ/Q8AXu8KXCMaGaDx4Yr3JqKLvtKstFHx2S3L3XWoAeI1T0L+M1pCQz2cE5WiCs7vI5BdWrPdKey3n89FPD+PzxBDYjHX/JxEU+ShMiQYMDl5eB1asn0KaNajXJKb5C0VUDRaixp6MlXGMZ8ojDClU0=,iv:bXS/+/3jdH7jiMLOvm/lbh1CJcaIut6WKWyu0opo8XA=,tag:vx6aaTBhrU4OCw8pTkd2NA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
