apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:Aq+gaNtX4UqQxxp+f7Ze+lZhxgvQegJmn01B2IRYwKeugwOgt+k7CQ==,iv:6QoYlB5yAYkJp2T7t1C9DEhgFzcJtkN6xiMASnuvBtc=,tag:/9A0QzNvgcNOYvFeQQtEkQ==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1jwlwsx5n7hu79qgpw86g6nuf35c6gauartjpehjgltwgv623aeasst9e8s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpZjhlaEhwVHFtVVpMSi9F
            dVdvS3FzZGZqWmRzZzNxeWw4Uy9OS1o5QzM0CkZTWktCL1JqM0R6UTJWOXhKNXBn
            S3BlM2N4Q0xWT1JjZURyanVPMDlhREUKLS0tIEdiaUhOSHpjbmxlU3RMMTVQSXRI
            WmYzaFlGZEE5N2o2T1AwSzB3OG1BbDgKkGNgYwohi3C0yvovlQYNJ5uq7oYYGxzV
            7u9gZArq6NwMjwOiayUj1Bb21jpO2xdXT/X+BP8+YsDI9KHLADne9g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-16T22:50:55Z"
    mac: ENC[AES256_GCM,data:2qDYNx+PZBh2DNQwewWSG+68TlSIL8y7LRG/3h8Fnst+/EbbEdnYO+WbS0dbosun32APoSJjyz6XHEtPu1aTnatsNO4aHfTNq25V9hbwVRKQU6eFZD7zaOhQxM/lSaJ1JWsZBDjUkZ2+n7Wz40G6IgJWyZxGLEHXuxL4KthV0ww=,iv:HLqJ5EC0sq/XrRXpFdMesuQLyUK0Jvzl25c137yqd+U=,tag:stxgwGVAw+Gpavwcrjb0kw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
