apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:kH8zP6Y6ot+vNUwweIdzFu7Oab3oS15ujtS6SNLHjV1PcLIEu3Eyew==,iv:U98tU6c9AztxlzOuhdXOnSd44o3zvCia/E+IVi0PVNg=,tag:wNcT6hyTY6Q6rvdBFAjusw==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1jwlwsx5n7hu79qgpw86g6nuf35c6gauartjpehjgltwgv623aeasst9e8s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQWEx3TUJXbTNWQU1MWTE2
            Wm9BbzdENXNTcUQ1d1FzNDhuYm12V1I1UnhBCmJIb3F0czZPaVNyY3kxbGswdUxv
            Z0dEcFFxei83VzZTelE5MUprOTNEOVUKLS0tIEVQaTQ4Y3RDV1pGSjFRODZGRWs1
            Mm80cTFFMUJhaEYyQzdrSUxoNFNpZ2cKKrloDe9TeLubDD/7AXnl/B3i37NoctM9
            QOZmuRID8dEiY23h03CoHwg72ir60vB6J9uTdoNfBDea6X0LF/yOvw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-17T03:06:10Z"
    mac: ENC[AES256_GCM,data:kwFwSqer6+C18cbyUOPYBMQCjxpsniY3stsa3phJxutf/HyQshX8Bf+aSFhJMzNhAhgmKZlkaD/fY3QUrRVsNNiCmnOlDgDHDbVcVsJEd/hOMvvIywxwW8V1gMbmInn2vwUnG01DZL41PntdpZ/lZhbXDBoqeTmkPAbPIGDRco0=,iv:HLxkcJ/Bk4jQbtKRgY/jq7D44uaJTmBloPOVkzjscYY=,tag:a5jS4XfvY0WTfDyKtpnXfQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
