apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:FNmUsZZPnA+Fft8Y7zbNlK7Ew+dsWzbTDjtzeXVZnw58AES5rItIBw==,iv:DG+EaGNFNb4HW0aKf4Pn0y6WgVAyw2LUnx+Rc31rJDI=,tag:/n3AMZsavfABPLFqTCFlLQ==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1jwlwsx5n7hu79qgpw86g6nuf35c6gauartjpehjgltwgv623aeasst9e8s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjZzlkMEJCK3FHRzRHNTgz
            MHJYYWxIaGJxRTFzWEkwNDVLZllTdGpKVzJRCnBpUkk5S0wwUWZWN0NHd3lDRW1x
            TGYwNllMN2tMb3JuczRVZUJncjRRM1EKLS0tIHA4KzNFN29wYVNZdytVMW5sM3Ji
            RTJicS90ZGhJUHh1NXpvTDkxcURHNFUKOrbNA2DNBgkLp7dXx1okDu4zQvYVx1Op
            OYreuX5e4vwUvZDXe001dSaeiuskA9kWwtovI0sA0dEUv2J3Hdcqog==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-16T17:45:43Z"
    mac: ENC[AES256_GCM,data:U86RBlruYsgWHBdMr9vNC4YhnOHJWepbHLImD2pudXqYWOvlhMAFapRa1yF4WOUSq8+VwpU5dKo3+Osr+ujpWPXH1GiaoGayrLOZaTkXz8T/vr4YCDG9ywjU8xZs8gtLTzA/IzzxeiuPqxVov9exvFSTdcqSzcVdoRXOwTMX/lQ=,iv:XfbB0yvXQDJ7cF08UOUBY/RIIuX5L1zOjRVVlcJ1BO4=,tag:dvy2DyPT/LI1iWYpHWnhdQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
