apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:6ff3Vazk1GocWewf179Vme1VPij4gM7BOlHJU9ojJHfy91jm25rQmQ==,iv:kriclIU1K4AbDmPX+DVKB58K1ASn5aRmGUcUS46iw2A=,tag:HBIdhwVnVzbjohIvNL2gSQ==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1jwlwsx5n7hu79qgpw86g6nuf35c6gauartjpehjgltwgv623aeasst9e8s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNS2xUd1VIcXlMK3lsV1Zh
            WkhFS2g0by9PV0tEWi9CTnBHYk1GMTc0T0c0CkdxdjQwVWcvMmh0bTVPVldjYkxP
            ODlFVWxXK2ZUWHRCR2hGMnpQUkhidXMKLS0tIEpmUGdpWDF2aE4vekNtK2Z4UHY0
            MVJtaERocThhWTI1SVFOaUlwRWhPME0KQn8o0qzl0VgZyU682XkJEDJAGdJ24Fz1
            LndSZhYLM0D6RWEn+U1RhsxLaNA/WIHJYsU260MIqXOeRvl2kIO7hA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-16T22:37:28Z"
    mac: ENC[AES256_GCM,data:MwhIIQvVOYJVRSgHBUm0yN7NbIF3OGVA6+dcUPKEYBhV/ONmZt+Gp2Zq0hxBGQbpd9R6u2fiSMagK2f3ja60cD+s82ss2e6WCTJ8CesL9lzsXAGEhy1dbMTrc0q8Unkkq25sjc2C+/q0XXaqPzR8ImR2Uvwghy3eiCFHnG+YDZM=,iv:CgAcRX8YLkM6nsHVYdJBEA8xlYqDxw5aTF3peLCKPIY=,tag:GxwfHt87Y+UOCzxVLEF7HQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
