apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:/jUQgIia6rvU1FQ+VU44Tdjh5Rpzp5yWIlzmTm0o17hpDoWJmxxP9Q==,iv:8fWao5QxNmMHNkxBHbo+/m3fCWFzsi7MtwEKxdj1x4w=,tag:l2kd6sQmwLWfRkoeFVXfLA==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1jwlwsx5n7hu79qgpw86g6nuf35c6gauartjpehjgltwgv623aeasst9e8s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCQjVvMWplcG1JZEpWRk0z
            MG13ejdBNzRDSk9EY3kvdUllK1NtV3ZvSERvCmR2MmZUM3BmdmxJREdrM2xEY3dF
            WGtsczNJU3dNMVFRbGZYam96S2RFYWsKLS0tIDBoVWZOUmowaGoyTUQ2WnVMM0Ev
            dWUzc2ZDdWpodVJkQm9hbXBxRHk2cmMKUZO1TfEP35vlgKiYJdBAc+JJ2o345XYQ
            kngOMqIMzDdoBVQLMMGc96PpAFuWqRxH7K3S46899goIwaf0f5aOsg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-30T00:16:38Z"
    mac: ENC[AES256_GCM,data:QuFAU9Sxc0Zv1BXnW0OLOUGp2KOWc3suZ9SV+c+8/j+YYHH4hqaspH5ttqple6TagJw0glsVthy/mrKBANfhNjwIziCyIwPNxUKrqjxWl7CqWlc7+XvsZLnnnITZragk/rSMJnQVAb7t5mg4iE/9AuzOubN7G9rlu21eTM7rpn4=,iv:3JGBfTngH/t71kjIVPN7MAXWso1JkduaAO5Wc+7uwa0=,tag:e2sHXstG/BEFI1Qt44nqhQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
