apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:u8rfu+uedb6yjIHRO7qwVvBhgv8BrMonb04fCTvd0nUianZ75Ffttg==,iv:W51uxVZImNWiV8PHEcuXuWzkneettRs2Dw1lP2CjWp8=,tag:IVHd+GUD7tlnOzjJRn5EOw==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1jwlwsx5n7hu79qgpw86g6nuf35c6gauartjpehjgltwgv623aeasst9e8s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxYXN3OWFRb1Nmc3JIOXUy
            TEs2c2lYNnNycUVzWEp0ZGJaYlpFcWN5MUFFCmVaU0tJMVNvU2ZNSCsrNXpsSStD
            ZXllZjlFYmRiM2JoNFVOU2VOSjI3UjAKLS0tIHZIeXh1RFpzZW5jOUxPSFczdHJG
            bUpEZXh5N0FZVk1Mbk9zbk5nc0crdU0K+VjTcWzuoXLOUkMbqnyUYZceDjcSy1g9
            XVUyr5Q7YB8FfyZk7VYKqlu1zvKcl8ft36+WPlpnr8ikYl26BiFnOQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-16T20:44:48Z"
    mac: ENC[AES256_GCM,data:ynAn9FC5h2Uluf5TKc33moGYB0csxdqycnWqiilDxw+W3daUDwb3HvE3pOxO3pXQ7NI9feoIHKmvWcAd5hIA83oa2jWhvOi2Z3nf2RcSkI57F7AymbRPu38J5zAIelqmpw40sXew9NILpU6WTJYzLcN7ADlNWEASMEybuG/Zcd8=,iv:HBoGiUQ0McXXCl1cAONMQ0BU5ImuuNC/m/EIEXizdEA=,tag:GdfLN/qc6Y2djZBo7/S50g==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
