apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:Ihkfhvpl9WOVNVa4QK3RI5iqn3Gnk8LZFeJn7wAyhT0yPmuMjGYnKg==,iv:BVObbI3L59YjLYJRBYEDUavWSk6zGfBh/5XGq0xuMXY=,tag:pc7S5r6v9DNMMuohpJWWOQ==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1jwlwsx5n7hu79qgpw86g6nuf35c6gauartjpehjgltwgv623aeasst9e8s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvNnFCdFd0YUZ6MFEzYldy
            ZGdndWYzaUZtM2NvSVRjRC8rdFpubnYwTGdvCjVtanFiOEh5MEl3OVdVSGtUQjJq
            aUJYb2NjY2ZrNjc4N1hoSG9LVnpjaWcKLS0tIElkYkZoem5qV3BoSUxxdTd5OFpC
            cGJKTC9jenByei9NM0dNR2o2OTF3VFEKE/HVQm06d+U7IdBKyEUquV4Sc2SIgLFL
            5/VpuLUFNJE/95LP1hyJ2lRQ8ovSBot7VzzBMdNC1yl0QQrc2davTQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-16T17:55:05Z"
    mac: ENC[AES256_GCM,data:jV5TJbsqU4dypGpChE5U30C8iINTE0av4Yra6bKfWX4yXCU0jwye0wJg5o+jilbsIolQVnCDpkUh8X1s0cPxNehMzEOS/OZujgCIUSuxFxKZiJMG40eZmEiM8fmfu3dwWNv5UO/r10+e69Bllhy/RubHIx9d29dTxqJL6Qxyizo=,iv:0ynKp+dRIHZzhy5vgNGImm3gH+z/s/YpMVnZoV7FRcA=,tag:1XUl0qTqQyyYTQTyU2Vm8A==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
