apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:KtOZEfm4oWuHWT9lUcHnI38Z7LMYihZAIdjZVk68sCgbQNY3BuInoA==,iv:gKXhRlcPxZo44tcT7QyOlTd+qANp63zKgS2xb9Z4un4=,tag:ptG2nlE4pzyPGj27pJFfSw==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1jwlwsx5n7hu79qgpw86g6nuf35c6gauartjpehjgltwgv623aeasst9e8s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4bWhPU0NzSmtvMStsK1Jp
            OEo1UmtsdlFJUkg1VVFNakxsa3IrTmEzM0dNClZIc2dYQkdSNG1LVi8vVnVnZDBl
            b0lKQkdNcm9yeTYwREd5UmkxS0d0SjAKLS0tIDY3QkVuUmJPVWR4OERzSGQwemc1
            K1lzWmgxNk5DdjlsOVZVNWpOSm4xWFUKnK4nfbSgz9qoyolRsqLObL09N3Hy41Q3
            uWPLcSnGaYuTDzcdLUd9MDQL7bzaMmMrjfk1MRAPP1+l7knSxgOmaw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-17T22:37:51Z"
    mac: ENC[AES256_GCM,data:NgU0a47Md4mxr/DFxvYv6NY2sZ3H6SJ4Zh2xS9mGFXA1V3qDNMfAvSwDCGTK1AKOSybCqqdmmjrJASlRO2wO1SJv0/hF8lp5Vz+RbuvdP5ZhJCgUkcpZ/Zca/FxjNaZTmgMCuWxzNY76GvR6gkZ3EvEgjEELSvfSo5GI7llQD+8=,iv:X2fuVWsAucZiIX75wKMVND4MAulgCTf3qpeBIVV2Jhs=,tag:TyGxU0/ofDjXGM+5VcPsWA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
