apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:5pHIAnCRzwwbh8YIcmQ/6F0iAxqSZs8YFbOxZOMq0GATtPCooqHIug==,iv:URTVILk5gQoOnkedTboetUSquR5v1Do8EtZ3TKAdth4=,tag:uTBUh9Nv7/ny4N/Q3pEiEw==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1jwlwsx5n7hu79qgpw86g6nuf35c6gauartjpehjgltwgv623aeasst9e8s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArNmtpUXIvUDQ5L0FUWTFp
            Y0ZTN2RPc3lkTmhaeDVEOW0yWVVaVk9kWFFrCnVZQmNJb0sxcGJQTG1qSU9JbVJW
            ZlhUc2gwQTdTTGZGVVowc1grbmIyQVEKLS0tIFYvM1dwTXFUNzZRQTlmMnpyNXV4
            Tnh6dUdkZVVkaFR3ODdDU3Zkemh2Z00Kfk6kuXbU4suwMb8sN5H74jdMC4L9iyVU
            Ye9k9nDoT9HO/71sVIHwo1tbCJ7zeIzb7YeVZFxAjDiVnXSi/NPD6A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-18T02:08:26Z"
    mac: ENC[AES256_GCM,data:gHpuaN064PExbpafKMvpbCRyA2RDQ9KrE7s/vYbA4q1vsm+9TFZB2tUinjsEnCbEi4xVuE5Cu7SNwmd3/jmPFQFgL2EIp3JeNMeKYUYTIxgPeu209SQA/5bXsw5f1akIx6Lg6UplxdE6S7s6FU9640UsGmKb/fHZBVq8coXpc00=,iv:t8d5L0P74FhhPReaEmVXwZ7DGqo9+ZQxZcl1WvhLu9E=,tag:YRa6pjJnnFp4ucxAH05/og==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
