apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:eenEdcBVuNFga7e3qTrwZ15vuFjDbJDxYcaYOi3tGaaWUa4oF5CQgA==,iv:kpkbpwPTlqoRf14RDZnDyLr9V/hgNlgRGNLkyDjTOxo=,tag:EZHpyGsttFWc4uttpmpAbQ==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1jwlwsx5n7hu79qgpw86g6nuf35c6gauartjpehjgltwgv623aeasst9e8s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBdnFlN0VYODY0QXZmMzVx
            OUQyZUExNGYzOG4raHRIMlNXYjc0eStWcVg4Ck9RMi9XMnJKY2xnM1pBQ1JTbXRH
            cU1qa2lZTml4a01UYjJwbSsydWpTZFUKLS0tIHBEb3dKeU12SUNRL0ZMaDZuR1BK
            bzJBTzRzWTYza3kzN3RCTGF0cjdFLzQK5WBJM+zdGSQ0O5P2PS/8frEP2+tNGfia
            ZeFhu59u5ugC2yK0kgZeJ4cz9urjMbxW1eT+KlHg4TXfLehBPSxOYg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-27T22:44:06Z"
    mac: ENC[AES256_GCM,data:izi/IZHBstMwam9zgur3v83ByTyPOuJionqWItTit44gtm2KMubdVyHQk59COZ+TNKky6wdeRfGpMRNA5d/I9M06G/JnoYx5F8u7zLWNcfyX6X9IbNOm/1N6LlrWIY1ouEeqLQhPzCd+pa2YbIsqpfdJXtblwhvMm4/f8t4XaVI=,iv:l4wpaJTg1iR19MbXgdvQPG4HhXgCPUPuS22MDF6id3c=,tag:kAUtc38HI6wbRhtAZoB2JA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
