apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:Hdoy/BNcelk/EHjXDsEyDrT5U/6H8H20oPdkkmGrnXEySKaIxku9FQ==,iv:pIcYKC3mjWSn3g/hbljRbw9AfxGtN76dWo0dxRyAVnI=,tag:Dvb69guUDgjOgvbyhqEOFA==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1jwlwsx5n7hu79qgpw86g6nuf35c6gauartjpehjgltwgv623aeasst9e8s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVNlYySm5SdnhOaWhoeG1j
            RVJIMmoyVXdkajNlTkl0YXJTR21VVjQ3dVJBCkFxOWF6Y0NrU0p6bjNFalhiNFdq
            NGxCeGdEcEdTWURCL1Y1bko1ZEhmUGcKLS0tIDdkdWUwVVVWbnQrNk5oYk5GYmsw
            QzhKSzFNaDFGR3hKS1ZJbDBOaHIybVkKlaLzqPl+bfkMwuwWNZHLVDGdYxIKQ5ci
            iclrRzFNQHu6cAfeKGKD5ifIuP91oxZc4S6NeZcdw8eH56QNxB5oeA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-28T22:15:21Z"
    mac: ENC[AES256_GCM,data:IGa8ZxaG6nMpQ931rkQ9JgevNR+oWCcOxUsxeOiVAQMKE6oNxrc1tYj3asUlp9xknNbuY4VJ3C9sxCjPFgbzueiTVbZpwR20dbk6Tfd8m6oRZxKzXpiIjDlai7fGyF3M0nJISy//GhrhIfaEzMS7ythbH3LbuBCJux3CUfCt5/I=,iv:uwCcMODxMJkO2VmFcoygqLannzFImERZ781InUFqQMI=,tag:H8Kk4qwHd4mwrcGwRoYOGQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
