apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:68kHZPGCQuxXm3G5/bPanOnha7IswllMsaCm6x3A+QAti+NWYIS0lQ==,iv:VQH5veddXvk2y7qny3ItJ4j5Ntd8HicBNtO0C8PWmIg=,tag:SX1sB9qTRqsm55nPq7RRBg==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1jwlwsx5n7hu79qgpw86g6nuf35c6gauartjpehjgltwgv623aeasst9e8s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxTHE2R2ZRWk5lSGN6M1Mz
            V09HS0VnekswZ3ZnSUthT2svL1FrS3FvdzJ3CkhZMEM3NVB6SHVWOUE1UWxXVis0
            aFVhSlBIQllGY0RyVDBsTGs4cllqRnMKLS0tIHlJSlpGcW1iWjJqTStQN1VQenpH
            eEs5K2NIaEl0RDRiZ3pmTS9CRXBDK00KD3ZoAxmVEMnJLts6i6QZySoEX2UzgdLt
            8WbMS863EpzbSHMQkgfwLngN7TkRiCUpJbxsqwsjPxkSbATTffHsgQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-16T17:57:00Z"
    mac: ENC[AES256_GCM,data:H36M30b/Zh2i2WzHlmxsxY+hUXU6169tVRi6De6IwUJQAEVtCmh+jqfTZO9a038Z1W/vgjuw2cBMeB15HCiVHvgHBb7MO2xa+4Ocm6kI6Y7quTL0NYxSrZ9oXZla1M4rZzESwDokF3qwF0ItEGcZcua5fU7EriQKFSqWlLiT6tw=,iv:3gFaBd56K57ocrJzO3HtqDJQn7Mq8BmacdrgRlH4kYg=,tag:EJNNPaeCGpkRA/0ui2WQNw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
