apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:DFQh7GGOZTmKioSxjD9BzHoMdjT4IwJqLxNSZd8PSPlWOQzkmtCB1g==,iv:Qwttu3pXTWjYhg+zd1zYIQKTyvKUvGdIusf/p2BX+/Y=,tag:h7AiQL+KGIPKpQFhXLfdZA==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1jwlwsx5n7hu79qgpw86g6nuf35c6gauartjpehjgltwgv623aeasst9e8s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLUFpUcHBRWWNHaEF4NEF6
            c2VBYUtCV2ttOGdhcG54bUZrUC8rWFQ1WkhzCll5RmsvV1I3dlRBdmpIWkUwcEhJ
            WFhSU1V0QkVwR2tHMVI2NHRwWklsSkEKLS0tIFRQeTdvclB0dUc0S09uODB0TUV3
            YjlDUmJZaHB2WWduVGhyWmJFZ1FpRGMK7klN2xULZ6Zf9JAtAKBu6zRFlCr/nKtg
            r62JI8COD4LC/1NTte3fru0SqRABovMB6r3rtReMnWiPndlrtU64kA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-17T14:43:37Z"
    mac: ENC[AES256_GCM,data:FPcRUD6CI172U6qpUnLexh8l3QNmvs6AoB+6DKWlAL7tvGjD8YTKn2cNvgzsO0Blc8zEdtiID5oer4liZ7OXxI83TdyPjyFA93RK1/vbxJhTyMQWKVzCJNp+UtT9Sbko1MkDperD7O0GMd1YHankVGQKVMrAtgBnZXAWBemQmVE=,iv:9nn3eyS2P2F577J1j2YDfvgRirEYdMMlVL8rfWjhXzs=,tag:t/2cRc9gBk4Ws0H/67I4MA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
