apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:kr+AVg4UzPlnw+FCLnzBbpS+fSnQ8ljHl6e17N1qXsnZMbixmb4Jng==,iv:ecDXxxTMi7fwgvA9ZOFkT/0cXlZuGF9h/xtgoajknKA=,tag:CKhxLs6ds1s8gIKhjN6Wjw==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1jwlwsx5n7hu79qgpw86g6nuf35c6gauartjpehjgltwgv623aeasst9e8s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmNVNnMk5EekVlNkQ3a0JV
            Q3gyVXFVaEUrREREQkREMGtXeE82a3dVVWpvCnZnd1RtRWdxQVJLb1l1ZjFCT0lh
            T1JOaHFEZkxQUGF1a25hYWEySElNYWcKLS0tIHZoYjhjcjRESlFrWVlRY2Q2cnlz
            VjlVWkg3a2N5VWFMcjlub3BDaWxiR28KQdD9x02K5TY8Plq27NI0v+qIMQOt0gHb
            tE2dX/1LrJG5Df2Xram+tcDar6IuqhD/6WsW6108lcKMzMxvCYZOpg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-23T19:42:00Z"
    mac: ENC[AES256_GCM,data:Is4+E3dqGTyBeUrpXbWLqUdMivnHggCeh1168gr8u1JlK/9Z+tO1W/c2zb8JJG0Q88Noj14PFLY5/ZEuTVtgSAnJc1yy+ckTfQKLVdKZpck4WW/C/muhDUOMfmGjSWharfWQ9dqDBwodj9PEtTXelZToCQnFxXycIkSMrPd7XqM=,iv:qC9WsV22vDmzGpr5e+AhwipSzlO88cqgq0V3Tna765w=,tag:1aHQ8r4FiRlPofwzP+jFQg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
