apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:f927A46nqVbdQz645LrKgGQAlxmitEGoZZE24+ot6fSHXu7hCVBr+A==,iv:g7GqR0x7tuoul+c503jmFIiRnk3VeUou+vL8ePzRLZQ=,tag:acCh74WG6najE9caBW3SGg==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1jwlwsx5n7hu79qgpw86g6nuf35c6gauartjpehjgltwgv623aeasst9e8s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrVEZpYjFud3NhbHhHa1hl
            dC9aalpBMGRsOU9NWVlycDBBVU1JVXVhampzCjVKMzJRdy8yaHlBR1RzRUJWdHpM
            anBiWWJBV0tLTXBrOWJnTG4zTk9ISm8KLS0tIGRMWEFUZTVTMTBIcHRnanRneFdF
            bUNDQU9DR2tnbVdReEhFejNxL2FmNjAKqI5ujFOK+OuNErQ/Gj5kx9mxLvOZKzV7
            9MQkz4NL1TmjLBQtijAZfi7gyM1+Q5E2DnSBgCJo3pQbxuzKNmB2Rg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-13T14:31:08Z"
    mac: ENC[AES256_GCM,data:Ov9Ujw6ppW2yK+AjcmgOhkyXzjKOTGkPg6UfEbZNQu6l4Dt6Tf+VaCKWAiurXWudrW8xWO2V595EI2THRhJw/QBMuds9HH1TiEIZAePmf8GcaGD8HVpgUSgaoFVoalPmQpX8mYnKBVZAQj4tJmWltRpe1KP0tkuIOGOJw90gjFA=,iv:2XVlQBCUqB1R+9B4gSaU95RDCxe8Hw5Cx1AbVoNsizk=,tag:38qrMY/MPlbdrzEFlaI8jQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
