apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:4jIKSQhkFFEmmn0K5RRL0OKr2vYHeu74Ve3/AN+11TL++fFhepMLzQ==,iv:J7WhgJtHUGtLZWZ1Elo9yDqdYXwtQrswhLafGzLVDEI=,tag:JYsdUNOd/N5eZnwkF9RRSQ==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1jwlwsx5n7hu79qgpw86g6nuf35c6gauartjpehjgltwgv623aeasst9e8s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKbklwZ1J3akFIN291UGRi
            aVMvU1BEWWdZS3V5dGZxK3RwVytmSGZsMUJJCm1KcEFsVWpUNzFVb1ZLbjQyU3Zt
            VmVEWmY3cHY0c2FUT3J1V2YydXc3OEUKLS0tIHNWTVNQSUpoUGk4cDR6S3ZXRk1m
            a3JPTmlzOC9hL2JzZ2FTbFhyVnQ0aE0KBAx4Tb1YzWceXSfeDBdxyiXfeyurE1DM
            J635OXt0uANRMjFm/odhxaPA6m3xzyPyv4vz479KE6uFkEy6aIMMXA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-21T21:07:44Z"
    mac: ENC[AES256_GCM,data:I+wUmFczRGU7XbKXGWvZh7O7K2uXflKWKLkMmbCO1b8lcixkdcD0HLbd2cqc+x7ZyADB1Ef6Im9WAk3GBq8XdIj1BWXnAuwyQLR+OnFZaoLBqebrOiyDfjFXKalawF3+DAvQq5vi04RVL7kiTXJsHy2kC2LoPLeIP/ywU1vCn6k=,iv:xiRNKmqugyAaHJ6n9aZXScfRvXJsjPHbfvNfoZgm/cc=,tag:ipyVGuH6b0j3lNYcribvTQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
