apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:6ACA6uGgxP/ZEBTkdP8Uk06RfXou8XKmmrusXWg9TYfX0WxoFTtHPA==,iv:qNis9yEmhygqAYzJAuEzmI7hFva4l7nYnUT1kvxiVG8=,tag:2REJkDuhkGfmUnRbCweRzg==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1jwlwsx5n7hu79qgpw86g6nuf35c6gauartjpehjgltwgv623aeasst9e8s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSTVQ3MVZyejlmODEzbVlB
            L0V6V3hYMW1EQ2dRMWQra2haNVFQYlVPQVNzCmxYTWlTZzdWb0dDaVhBSUx3RlR0
            eUdJUmxRMjJBOTA2bnJKWVE3aHUybGcKLS0tIENBVkRQckhKb0ZsS20yb1M2bmdn
            LzBkekRpSTNkVGhHL1o4TVhTQzhkRkEK8xoft43/cGjnQtFQ7I4QV3F7xuJ1qAEb
            4mqcCsLbtdX/p2PwZMK+YmMeQ2sv5EO1dHUpLYz+dF/IHuW1q1Oxmg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-15T20:31:06Z"
    mac: ENC[AES256_GCM,data:I3zZBQsqLojRyBiEp5HQW2Xwn0vWaGAt/oHe9H2NCHfk548P5hfnzqNVzEFTw3vRWh7Iuii5En0/uqthSY7kIPaM86X32mS5Q9HBy/oFQ0UsHWlPIq2vjw2ea6vS7Qa6Sxq67MZa3LpN8UIxRi+0EsrE9JcMore12tMVq9+63p0=,iv:aLOtacIZV/xLwudkuH547ZnQhXqQOcmxL3X8yIm8XvQ=,tag:gbn8aLIi422k+rQAinD6PA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
