apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:TWlw27o0rLQ93YHkjkwGOEV0B5LQcxFvZ8bGSYQP7UULPvj25xjNlA==,iv:h+xTETq0YLBXY/u63W6UzTCjxR8jgLuhL993x7DW4Dg=,tag:ITEH4Onzq0ERHgQwJeZvig==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1jwlwsx5n7hu79qgpw86g6nuf35c6gauartjpehjgltwgv623aeasst9e8s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIWmgxNmJzNnVnQit4dlNo
            T3ZqU0NPMlhqaUhWMHA3TUs5RTBFb3lDOFhNCjNxanRMTS9ZcG1XU0VKck9NSEJj
            dE5WckhQT2pWdytwTHNMZUR0OTV0dWsKLS0tIFdYS09YV1VTd3lIcHQxcHpQYTlF
            UmRkeG5YOS9PSndWOG1pWFE0R3ZxVXMKRNg8tM3j1PZFk3YbtyFGo+WA68Uvzze/
            spumLxAGjZoFopxbmgwyuEyp86znHoj0Dmces1howM0j06+wjf3mVg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-18T13:52:35Z"
    mac: ENC[AES256_GCM,data:m0xK2YbIAjwO2pNkj/OPrqonMhtpXKGXAgATfk0u8tl3NWzkszyMruRLCDEvYVpNnF4VL91tUrScjBzls3Dh0jt2KPva2+dCVjhCTwpg0iuZY8umN/jk5FtWudjzhBQOYYojb8xRKiu5yNNpx4A/vuRa9s05ArYyLc0Fvh3Qwsw=,iv:esXaShxM5wPZ6DbV4UNu9ctL0eFfoMyKm5yS1RxBc6I=,tag:evP6ULTdQa+mfGkaHwF7xA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
