apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:UMPhLrH24szKM5WR9YfKa5oT87hYUXv+ZLfhJPQ7lRReSLrfk0KKvQ==,iv:7KD7X4ws6GktocX9rkWVv7E4EcaH8BBgcAgfdxrs2dY=,tag:xBCK1BNnXbS3MIU9HHKtkA==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1jwlwsx5n7hu79qgpw86g6nuf35c6gauartjpehjgltwgv623aeasst9e8s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHankxV2dFMzFkR0djb0RL
            MnpBaUtvU1BZc0FxdXQ4dTltT2V0V0lPRVRNCno1ZzlRMHN0cHcrbGE3MnJZMWdH
            cjBYbTZURS9QSDR5cTlhdWlMV29HckUKLS0tIFhKN1h4TkExeXpTbktKUnR2UERM
            TkM1VktRS0pUOWJnVDI5a1U0MldvTGsKZegkVnCsslN78rhiuqPG/qVXSIvbjdNV
            8oz4oD0QwPUkd05yVQLRk+flzx4MHqw4hdC9F8WTFU4lUbPjf5+sTg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-13T23:21:49Z"
    mac: ENC[AES256_GCM,data:o6jlVsjAMir0gtiIlymIEi6Ipf0fkhv6wAHZynoOxgabRN6s7vFmk7/S449ACqtVKV/zfGAaRlxhNne9tapngy1QtC7oi4UxWzMdiaAor/1SPE6e2tb6EsN2cFm6Rc6OmDXeROKeT1PE10w3R53rEdYtHtkTzByF/SHEZAebufM=,iv:kE1F0hjnwsnedcoINY93WKAxA64s7TIdOWMAAQ89fCs=,tag:LD4GV11G6oQug2g9JucTyQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
