apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:3glzbaQ/ZpypRWoK1TFQk2rjx0TkRCh529id4uy94f16soI0HkjkAg==,iv:uAtRVAx8xmoKYL1laJTWTJFX58HJj5aQ5kXR/axWYIA=,tag:+T6OfeMXo0DMQX9167nBQw==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1jwlwsx5n7hu79qgpw86g6nuf35c6gauartjpehjgltwgv623aeasst9e8s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTMXQyQVo0YjRNRTFNd3hr
            YkNzdVc1NHlYaEJRdERqMlN3WXFtWSt2U0M0CjUyNGx5cVZIRHlFQ3gvNytBNzVQ
            SEtZT1krUExUTnFLYjRubGJQM29BZ0EKLS0tIDBsS2pZREQvTSswaXBiM3paR0Fw
            aVloSVVTKytVQURoVTdoVHVZZ1p0c2MK3yiu/W4waWnMIul2C4O66fcKyJ3Q+Gcc
            4cfotkEwyGqoeg9anZZdHX7wobCqfEz7MIeQmAPxb/lwMoL7pF+Crw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-16T20:30:05Z"
    mac: ENC[AES256_GCM,data:9vUVuUr/Ypz2Twgd6YBltfPTBkce0NGVJBYuYfn3H9AviCJmgVdTtJPMclpzY7GBZ+EHqF+QqEmW+Z0J9Rt4KpjnHuusC/iR0iLttUgo+UtDVpCMs3ex8oYDXFL+yaTNf45huQ0UpttVXo/xyO1PRbWn5X9LxNVRDRUzamNOOv4=,iv:vTqY6qpDrI5xAQtKlKSRH8rwEN66rcr/osxAe/JKwbk=,tag:LdU8QOcIDG/redWASjAO2Q==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
