apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:N70WWIKM0WjLR59OZ08kXtae5tvLOmy1G0v5KHHItXBSFUcKExzwNw==,iv:Mr1CiOf+MLrapj4E76nOCsYb2kkcXgXgMGv+EjbAEFg=,tag:KHGQilwz04iDud3ojam55w==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1jwlwsx5n7hu79qgpw86g6nuf35c6gauartjpehjgltwgv623aeasst9e8s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvSVlEc0NTcmptVVJ0VE5p
            M3U4WTFEalc0ZjZMNmp6bzIxUUpBWlF2ZVY0ClhVNjdIZjdDTUVxT2NmS0RLdWsw
            elg5d2lteWxuYTRJRzNUdmV0aDZmZTgKLS0tIFhDQXlEM2R1UHZHcFprc0N3dmM4
            bW85aWg4UURUdk1pb1MyRHZObndGY1UK5I0cVQWV6rlb01hExa6YxYFQE7IAxj8l
            Y03VSpJwPYyGRTuvqlw86mvhY/9G7Y8PO9P9WDkFhV/xEzTF0hqI5A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-17T21:17:42Z"
    mac: ENC[AES256_GCM,data:QimhbAuBvRy5ODrt3yIr8e/vkQSp7NdEVQCUJ9LucSMUgYPe3jC3aqwelxczgTNhIXdLpCqV2dXB90T0sCFTbbVHZ90doztVSrhCafBiQkQTJVRcR0G7HajcoADx66n+eDus7EckJYjnOFJjVr/GU+0bb0/d+5E2UB1ndX9KDF0=,iv:9bR2Et3I2pM9S4jA86lRl9d3/Zp8Qv1bedtY3avZRv0=,tag:Jecyhp4N9Cp3lCwrHFx+aw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
