apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:UDZ4IMtOsGV5ImFg04w4BIqpIfKM2Gp1SMQ+J4ECCbBnRQhVM4OUHA==,iv:DsX9mbQ00s13C/eE8tCbQMK2HcAKAS/sjKW3TBBO9iY=,tag:jOtwDiy90oihX1LHarxpiQ==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1jwlwsx5n7hu79qgpw86g6nuf35c6gauartjpehjgltwgv623aeasst9e8s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpYUlnWWZPTDAyQlh5RXhm
            M0l1RXJrSHd4b1FEY0NwaDRDV3ZlRWFPQ0RRCjBUd0loYUczSFl2dFhJL1prNCsw
            NSsvaW1CWWZpUnVPK0JxeDUvTkU3dEUKLS0tIDNOeWF1UEtZY1oxZUJKM1EzT1Zo
            QVFxQm9ZbWhHWkI3QmxvRFdnc1JTS1EKMMpnivmg49fOtw2Uc4wgC9OAdYsIjAC0
            U6LkXhZxfI8RbJPdHD3VRo4J7VGl1KHw/IpaaXJieuyn78cVbNf11w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-05T16:06:34Z"
    mac: ENC[AES256_GCM,data:gOYgvtCtSMwkJBS0RdLaNAHOc790X3beps6fu4SegI53cFLLXxgXp+SRyQAzYtNF2BuWLUrCE6IOPodPpEwR0AOyBosRN5MFDvDQLk0jWV3ZVIinbysY7LfDIjS9X+uTZrIM3CrXJJ2fT5AFbsg5KCUick5y0zgtyMe9Sgm4pCc=,iv:sNTsZ2FD/FnATYxXzVw/HCDYm7VB4/7ceKuFTTxtY20=,tag:O3zcREBwEuMMm6yP9o5Y3Q==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
