apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:Fyp2908FPtYkHpYzNYb1b9AQiXm4xLoQnc3FRT0HyC0Q/o1kkc1f0w==,iv:T1IpUMJuIUOUOblA5yhJwofJkgrRV9aF8+ljAiHf2PU=,tag:wXYErRU8WxP3Wi+bmsRWpg==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1jwlwsx5n7hu79qgpw86g6nuf35c6gauartjpehjgltwgv623aeasst9e8s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkSzBGcFdpK0lydU5IbGt0
            WXpCcW45b0ZqR29HR3lHYzZiRUQ0a3hHVlQ0ClNsKzF0ZXhHQTBoQXJ3L1VqQlJF
            WnhDdVowMkl3ditpcFJyK1c0RCtqSDAKLS0tIGUveVV4SU5URExqWW1LSnV1S3c1
            WDh5VE00NmQxS0tNcGVuZXdhVGJkNk0KlGKcv93aDWqx+p3OASjBflrhVYzpe9iq
            8Bh2ZgH5B946p9kCij34EtKj3orINlAaXKiRwHjzhdHVJwn6ULRMgg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-29T02:55:33Z"
    mac: ENC[AES256_GCM,data:NLbpHKVOIIAwGttao69lD4LE/xiyaFaPy2WWmlJ7jU9w0oNWLFvwoE7GKftDT6LgV274WXRaQ3iyJIP2biAGMtfAh9qCvWUj4hnYYSr7hmjrWEcO0Rt7R+hvykC7afx7vUWQGKXC6AJoB+IQW865sWZgk+EEY2ZVKNzjbhvFUuU=,iv:EBf/lx7Qt7C/5kWqlPVxRfwm+IgVLnZmiQ6ieFovWBo=,tag:zZkl7njGqLwCiY83FFr54g==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
