apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:WHVmh78iQe3wUJ5/lY9tWSg6if3OR6MeCMIp6RqlWCPuIJrShT+Xdg==,iv:1H4Klm52nDFbzBjN/J4yg0l8DCtbHP2x/Jx9S5nNNvk=,tag:vkmisfISBFiNUN79D3pwCA==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1jwlwsx5n7hu79qgpw86g6nuf35c6gauartjpehjgltwgv623aeasst9e8s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArOGd2STRDRlExZHB1dmRj
            eTc2VjV5eVBhMENDWlBhQUxScCtIMXBTQ25JCm5GTTJoL2t2Q21Vd1lQUUpDcmVE
            RGNZNW5XRFZiU3hWeHk3MUgyOTMzZXMKLS0tIExwQWtuVXBFWWJQZlNjUkN5WXN4
            THdjaE83NDJlOXA1d25OTmppNEEvNU0KHfGj3Y028pWEk23wBnWvWEF6xixuZc1s
            3mg7ffjJhowUxXkFhop0U94DLSKo+Z9c2iqluZAeqQL2s+YyhIJk8Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-17T22:50:19Z"
    mac: ENC[AES256_GCM,data:tDHez2F+3g240ss8eT6djv7gVoBAjDY7eyl+tGNOUoxkAQPn5nugNKiqLdjCRGrj5TfaVa9T+Fkx4jUEewPOrjDHKT1BurMy76YaUS3BE56Ws0VJznhrQ3ky7MVEZc6fRyEjdntF3i5nl798tYfRhLYbgJwaL9zq5A6hwtrr2vs=,iv:ylFb+smgqEcDOqJWy0ZXdrSJC6I3o67DliFO61aUj0Y=,tag:L+g1ctMxN+E+bEMc5mnWYQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
