apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:iFOAtATsolYTiQZjmStOYwrag8oufuCSe41u+OF84tQs33Z6eKXFOw==,iv:OcwriTW3mAItp5CK38hF4r97w/3t5mfFFdrMe7tzOF8=,tag:c0GKYVgi0uHjlWzEGpfk+w==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1jwlwsx5n7hu79qgpw86g6nuf35c6gauartjpehjgltwgv623aeasst9e8s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5L2VUdldRakk0VElia09i
            cytlU1E5aE5POG9PZ0R3blNEcGdxTDIveUh3CmtjVDNqZnZQM0NVdzRKR1Q0NlJ3
            czVnTGNzUW1IV3VYblZHdDJtNlZnbW8KLS0tIEVYQWFrOW5LMXJndysyamEySzBS
            c25hV0FleTVTTjR5RytBK0RjUXNQVDAKGjDIPhxdHwjf4gJmXTrE9nanONCF67HN
            0vzVN9Gl5wsM2O9cCuWw0ftxrFjCIvXhGnOMbVFifyJxLhBYqctT/g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-17T23:12:55Z"
    mac: ENC[AES256_GCM,data:gObxH0FdxeBSbx0xENhNHkIXzhH1kIiTDuG/cPFb217uKTB+V0TAuj4QupU5X+XdzrgJWCmyAg4Hv4CZKBM7CVdnuzUGHolTunR36ah8abz8gdV9mkSHEVhpvjIDlIHVHWBFYvoA9I55xf33wtL6xDd049Fqd9AAfWDdq9a/QMY=,iv:aFIbpKlMorhoWXj4W3sMavv0+VlZmY0UIxk44jpdrRg=,tag:yK0ey4MVvdaBwvPhUiUybQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
