apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:nL63vDZpxb0mEs0qeE/9HIFWCMTH9Dmx1wuk71cMCmueQELSR67RXA==,iv:kF9j2xsdIUD0BFas7/TMhnmdU8GoWydfrfxa2ABDVOg=,tag:TTVSTsy74yiVFIjzAn8T9Q==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1jwlwsx5n7hu79qgpw86g6nuf35c6gauartjpehjgltwgv623aeasst9e8s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0emJkR2paVXVDSzBBSTVN
            YnhaUlRsWXlzSjRJTHNUd05kbzBVdzZpMTF3CkJ6VUVNOXdJZkE0Z0Jxalg2WS91
            NkpVS3JsTVU3Q0tPYzBmUlRNVTJpVU0KLS0tIFJjZVpmWWU5Q0FJWUNjSVIvVy83
            bngvblo3YmVQT0c0WE1mSHEyOExNUXcKkKwCtmt21CW6u+TVmuGOiosLkOI/ARsY
            FraO0xnGaKOXO1ak9OYzWDtmoPyg2LR2JBSMH+1KCSY0IqMFSjKL7A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-24T01:21:38Z"
    mac: ENC[AES256_GCM,data:unDkg+ohoBPTHNJbRzl85uk7q/hpHSI0jk/pSpGUMnzYmGOO18aoV+JPtud72gsP9CSzVNFB6s3ob4mwI4tacJc4Cbxx/wxzArPdKkESka4rbmFDoM2KOGBd7JtNEQ0YmERbN74ogWe1q9b4kBuOwyKGDpC2lQd1kPxoVd1bkCY=,iv:d0q8Uv6W0uNBXma4BfiAjQtc7UZ7vDWYqAFyDZH48WA=,tag:w9I3Jgav9Rxx+C43Ova33g==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
