apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:LgS2jh7/c4agjyahJThdPpmPIMgFvPsjDQVs3shoFw6/jaxy/g7vKA==,iv:oGX0GZGav6kFsS2M0xclIPiZ/eUAQKqtUQdI67DrLk8=,tag:/wpLDZxW9FTwvJ1ogQFiqQ==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1jwlwsx5n7hu79qgpw86g6nuf35c6gauartjpehjgltwgv623aeasst9e8s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0OEZlajdXa01sSFNUMGhB
            YnpJRjIrQlIwekN4djY3UVVYb1pRNnhLcGdnCkhSQ3lrTWlhOCswV0tpV1BXMUhH
            R1FjSVNDNU1IVXlOcXRMSEhTeHFTeGcKLS0tIEVOV0RCUEo0QmV0R0JyMnBxOFcz
            SzA3TExBdzNnRWdTd2F6bjl3aUJZaE0K2ueJEglD8B8wVBBYOoxh+EpiLg+ldqQ+
            gYSlL5CebXKYRpIzH5x3wfMkimAbN/w0yygG3IqUQxh7VBkfvBj09g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-21T21:10:13Z"
    mac: ENC[AES256_GCM,data:dP0Qv3tEzFJVVt4d5u9/9Wj+7b207fmpdIdKOP6fq2diCnKnRn5P0clj8+ulDgvB7v/mlIvfLan2d41OFasfo4RcAvTljGLqAw5n1hVri3mzeplwy78Gjr+r9Kgx/ooPjqtx/pCtCcnNn4KrI+FuY6zjKIr3ROLbIAQTWJH87kI=,iv:N0AJsE1B0JDoB9wKarxru2b9TGYVHym+/VZa3ectt4E=,tag:XS6l5vRJFPiGhcRcczUm/w==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
