apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:Sn47e7i0qp0tbqoLAwrLeV/P+T+/eNWLI/4WHdB5XkbKzsfs7V7fVQ==,iv:OgM2f65PzYzoucHvZNF2l7+RPw5pCzAHwyy3BNctAwI=,tag:QYzij8ZXiI4v51ZU8OVlhQ==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1jwlwsx5n7hu79qgpw86g6nuf35c6gauartjpehjgltwgv623aeasst9e8s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwRG1kK1lGdVRlYTUwSy9Q
            UTJuYWdwTkxKUUd6M1pFRERibFRjOFJoM3lRClpJRGkrUXNiakowRFJtWXc2UUFm
            MDZoQlZLSk00anJSdW9qbDhFQlYrU1UKLS0tIE9DenZWRFRCS3BCeDhhcEw1NVZJ
            TlFPQWJGNGsyaUp4QUQxQ3JLbW9pcGcKJIhEYr99JaABJOgYlGg7xt+mgIhuT+Ni
            lPABqveybbmDJoVyAA+x7HcbE/fOZiGM2WyaboEXOtOSvCfa+hU6nA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-29T03:17:20Z"
    mac: ENC[AES256_GCM,data:o2Af7s1q5X75MmLZ4svEZl6mw0GoVXe7MfSVWfxb08RswMg5ZgP+1PlLRnnBlPwmm/N2c638uoT27wRqc93GlKR0PIoyTN/4pYZjDGtY40Zxzt61vMeR8oL7xsAGevY1GsfMWnx0HCCA+y3U1qc5KO7bD7xMWKlbCMyRYXtYVRo=,iv:y/iMFZo+8W4f5YCbAY0G7r4x+F1haiZNj4NohY2Hri8=,tag:AJKfLpcupAnWtnFhRmt3wQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
