apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:k2Yz/AtBpLnUdnEbnTJYxGbq8QZeuk2bG3B1OfMAeQ5Jvs5ZUDs76w==,iv:M++D4wN/UhGaw+q6zFpGxYxaiR1663fJASaHbSbEsuE=,tag:CrpPLLVUf7VJiwDBGIdgcA==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1jwlwsx5n7hu79qgpw86g6nuf35c6gauartjpehjgltwgv623aeasst9e8s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQeEJMS3lGN2pDVzN2MEh1
            Z2czL21nZG83WC9ucU10VTFBVnhCVnArRlRNCk12RmpQUEVYUVQzVkZtVlIvZHRh
            ZWFtdmxyKzQ2ZjFoRWFLN24wVkx2Tk0KLS0tIHVXcWJPMnM0WjhJMHZWazVybjgy
            TC95dmRkVVNFOFdGNEYxQnF3c0ZJMXcKDWlumH0UUNjiLNybGIvJt12Qtuez8Piv
            64KDZatzVMtTLSDo+7wJvXbZfj+kXUMMXehu4cnbnAkDmqtM/Bj78g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-05T02:19:58Z"
    mac: ENC[AES256_GCM,data:VYmu+/GMuZeEjf9rXp6IzOjFZT13s1FhY3CiRyGg5LYgrns8sXmqr+C7OuLU0aGFg67G+UPDc44eULX+T6aoLdjFJuwJoLjKRwgSRiSRKtGtL+UlVjvHZ0kPGYMCBTuLvtcW25G9yl4EcrWRssbNwlzrRJpMQnpfidiHjeU/45o=,iv:xSTYT7gHVl5RzxE/S2gKeOPSsD5Q0KAF8HPaRVLqSRQ=,tag:VapcKwjvtCzYAeWNo21kSQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
