apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:B4LBHOqCNbWohGoX62UQun1D3q0Rsu1svqh7N2bs2AwnlVD7LGJpkw==,iv:yhu5CLFcCUtD72rc915JOkuT9gElF9AjPqgjqea4OsM=,tag:uFT3dDFON9XwYyvvrpDQ6Q==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1jwlwsx5n7hu79qgpw86g6nuf35c6gauartjpehjgltwgv623aeasst9e8s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJRHM2N3JuSFVPSU5vOEQw
            TC94UjBVU1ZoaWtXcjZDd0MyZXZLV3lIRHhFCkZCSTVCc3ZONmo0ZDFRcDVRRXlY
            a2RTOHRHUUtnRUkwVmlhaXpjMDRLWlEKLS0tIHFleEwvTnNhNTNJV3NnK05NRndC
            NmVVWC9vaGprOFN6SjJVcXowR3RDOHMKrCm7K+Fwj8dl36XAJtp+3YMDCKQ/v/mX
            0kBR8+6ciKeYMbvAnMmwwuVUIBmczS39HiY9fR/a9BIJX5tGznPQ9g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-16T20:08:57Z"
    mac: ENC[AES256_GCM,data:4/BipY3MamSAjqIBpi8MY8agRp6dxo7WS1jT2zQc9XZSb+mrH+Q5rR5xrKfVLcTXS2L6JQoT7H3pyrkEym9bQIbieAVOTedVCd4UdoSBdxQ5bHVsTynfS5E2vhqtMw3FJSbU7s9qIv6DBVqlbKMZmLNEmo3aeDrNw7UIvDnZwbo=,iv:DABaQPzkcURVrEeXpRVUa/uE6NZ7w5oMvfgDcLpF0GA=,tag:kWHrLHEuf6eVTEJJsH+xfA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
