apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:oRY3lo5/evDQqTU8uunSu79lZjfa6lkw8lVDrZrh0CpuqPKBUhXC0g==,iv:iVuVYq0LCRRiaVq8GEFm32yUwDkEfXMRaXUK0sbN84A=,tag:8G9uP8v2PQ4Hdu91i4DZBA==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1jwlwsx5n7hu79qgpw86g6nuf35c6gauartjpehjgltwgv623aeasst9e8s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtOGJBbjBmVWg1Z2QyT1Yr
            K0pudzFGcE95b3FzMUNrdnVmeFM1S3QyRFh3CkE0UXlrakZsUExYQUM0N0F6bDZZ
            RUdsaDhzbHd4RHc0TW5CeDhzdUF0RkkKLS0tIFpiNFp0NEFSd3o3MmF1UWNMV3lu
            TkptaWttNXFCVVNmNjdKVlM2TTNtbHMKb3qRcfkRIXXvRpkz4QAqb2mYcvcwrrSg
            2TiOQpYDj1yFIgJdNciu3MFr8YFy+o5xXd/GIgMeE6HHc2JTZey01g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-28T23:12:18Z"
    mac: ENC[AES256_GCM,data:cvKC81B8QKk7Rn5CIH23JyzpO3eu10j7psFZhTh+Qj5eQWtdMpLV0Q2o/ThIwaZn8/SUbmN0WEPKsejmYoY0YC1BnYPyLmqW4bw6A4LfCQPfDdHgR8Obqb6/9PPqGw7AA8SatmzaqylkVTjT0D13UaJQbp1fqeZEzNfzAxNVRCE=,iv:KPqk5ClbMqLqcNVWzWFWrmhgdXun4c8QSgsoMdPewmM=,tag:c8wg5TAmsOIDYbryK0yl8g==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
