apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:osZhPw894euqkp3Mt4RXPStWfo5VeW09+NK4k8sikdi5yJ9dfutIOQ==,iv:vymVOeIUYpyJSdOKDAv2wgXjtBTY9C1N7DTZUccgG1c=,tag:8OreMxWkh+445NmmjS5uWA==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1jwlwsx5n7hu79qgpw86g6nuf35c6gauartjpehjgltwgv623aeasst9e8s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1MjE0emhJTlhEL0RqaTVD
            K1pRYjdMbElUcXpJSUt6ZmNuV0lOVDRlOWhZCjlxMGNMaHRQUnlKR0dRY0U2R3Zx
            K3M1Q2RLd0VoY3piQVlrelo5R0J0WDgKLS0tIFU5VU5WaHpPL3I5UUtvd0JCYXZH
            dFk2aHVaRHZUVTdXQjEwVUExLzBHRE0KZzjDjf/xMnVs7kSjuL2/hRyMxqcAJQbJ
            dQJ4vxG2TQAEQ8FoWwsSAvxdE2a9Ew6n7E1pIEG6yRdSXfwKyFbtuA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-17T22:36:05Z"
    mac: ENC[AES256_GCM,data:4Mbv4++A9U+TCzI+yTKF3gyx+jeUTunAJfl2dcaQL8crE2WTkKHN1JIqBavAmkt7y5NSzZeXk3wR+Rq3KS3rW6X3MBskSu0Tn1rlTxhD2XMfHRSVg+87cWikzXh49h1LtAZlO+u/dXJG1uAYLm+mlFiPtpQkJz+Cw12gcA9MNAQ=,iv:jC66nhwQB459DyZbuv8bWiLcTY665AS/xhEY5fzsHO0=,tag:cxLfBJxF5CQlgdbz/BJZ2A==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
