---
# yaml-language-server: schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: xepg
  namespace: xepg
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 14.5.3
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false

  values:
    global:
      stopAll: false

    TZ: America/Chicago

    image:
      repository: docker.io/mooneydude/xepg
      pullPolicy: IfNotPresent
      tag: latest@sha256:048608274d6087db024f7f8c4f4f5134af6d268559abc503ab71ee26e62d7c03
    securityContext:
      container:
        readOnlyRootFilesystem: false
        runAsNonRoot: false
        runAsUser: 0
        runAsGroup: 0      
    service:
      main:
        type: LoadBalancer
        loadBalancerIP: ${XMLTV_IP}
        ports:
          main:
            port: 3000
            targetPort: 3000
            protocol: http            
    workload:
      main:
        podSpec:
          containers:
            main:
              env:
                SERVER_PORT: "{{ .Values.service.main.ports.main.port }}"
                CRON_GRAB: "5 0 * * *"
                CRON_GRAB2: "5 20 * * *"
                CRON_GRAB3: "20 20 * * *"
                MAX_CONNECTIONS: "1"
                DAYS: "2"
                DELAY: "500"
                TIMEOUT: "5000"
                # SITE: "zap2it.com"             
                # SERVER_ROOT: "/html"                   