---
# yaml-language-server: schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: docuseal
  namespace: docuseal
spec:
  interval: 15m
  chart:
    spec:
      chart: docuseal
      version: 4.0.1
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  driftDetection:
    mode: warn  
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false

  values:
    global:
      stopAll: false
    credentials:
      s3:
        type: s3
        url: "${MINIO_S3URL}"
        bucket: "${MINIO_S3PREFIX}-docuseal"
        accessKey: "${MINIO_S3ID}"
        secretKey: "${MINIO_S3KEY}"
        encrKey: "${MINIO_S3KEY}"       
    TZ: America/Chicago
    ingress:
      main:
        enabled: true
        ingressClassName: external
        hosts:
          - host: sign.${DOMAIN_1}
        integrations:
          traefik:
            enabled: false
          certManager:
            enabled: true
            certificateIssuer: domain-0-le-prod         
    persistence:
      data:
        volsync:
        - name: data
          type: restic
          credentials: s3
          dest:
            volumeSnapshotClassName: csi-ceph-blockpool 
            enabled: true
          src:
            volumeSnapshotClassName: csi-ceph-blockpool 
            enabled: true
            trigger:
              schedule: "15 15 * * *"        
    cnpg:
      main:
        mode: recovery   # Set to 'recovery' when recovery from S3, also change the revisions 
        backups:
          enabled: false  # Set to 'false' when performing new install (recovery)
          credentials: s3
          scheduledBackups:
            - name: daily-backup
              schedule: "0 15 15 * * *"
              backupOwnerReference: self
              immediate: true
              suspend: false          
          revision: "2"
        recovery:
          method: object_store
          credentials: s3
          revision: "1"

