apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:e7GQlSG0XNvLJypTduRXlBzD4XXn66ofg32dDoKnCUvAhcimR4xEYxUB6QjXYfBQ7ElsPKpAZxO6GvdDOKPh+7fDwjc0Xo9Bb3ScQA5VWS6/MHebPSXVyJIjkVQM0PaASwkC7Cud+FZGvf6INRLJLmIFq7dctPQX/jGzC/M++P3D6oRHTTAckcMKA0IlHmZX+ca1VCpzuQ8S+s1/oRF74yL7AuEKmTs1hUso3tQsfffUdDNm2JmP/Bue89Qr0xnzuuEZrlxI9xUE3KaWtMerzrKPNTKSQOiCyzmfvr6qW8SxMski6LMtzEnyqnrJlfTXr/ctuG8VXI0sKWFF2oltqD4pIolyufYCXs3hBF5ko3flJYKmN/HIpdPVp2ypao8O,iv:Da3eeNYqZuSoHL7lzFrRMAdbLgegEbInhe1Da9NUehU=,tag:FwZfMopHD8RkrQZ6uipGxg==,type:str]
    identity.pub: ENC[AES256_GCM,data:Fq0RY3HFxiz6wTGZck7W6xgns24tSwUlUIlUeEtk0WJzZhRJsmLzGxwIuSMmORwaGzSGA4AasYlJLe1GQ0gYWdTuSfE+ybIuFpn1z2FQ32y8M/g/NkD4aXCkKmWx1q2Z7HsAU0jacIb3tNvDeU366JFru854YyamgjyhRwrR42TNx3nXTDykoSVtNvFAXff2V8yFf1iI6RfzD+nWAunLAi470e+ZTekuK7iMN9vMUtHiPBdVJyG/XvCmQGvssgdr2Yl54rRr16EhJkkBNw==,iv:r+04wNv9m/3YP0/pepOQ+KZwVhzzw/VrI8VZ/38ytac=,tag:FhaWgw9T3fdHdjvqDBqlVw==,type:str]
    known_hosts: ENC[AES256_GCM,data:QzNexbNUnYMDa+h8+GtSDfCjuveFTgYRF+kKHYKehd9rhb67ODkeKD9JXF7B8H2K3bDD5xfNoB0VETSNCpl6VF8SFfJ99lVHPgFJDWxvvygsqHT/YuFKcc6llWvupbDYhwm44xnFY2GsgR+yPvVtGluYkoVqjyvGmrkb9oeKdfz7TBkK+LPMfFwWQ0xG+1l3V4Rpj9MbH6byjZNG3SaNIn05nIDg5gueRbRK,iv:b2H4QVaAVIAH5F8wy5g4Zq+g3hWfHwTTuj+BXpwQfrk=,tag:xNoIijVPNTySBwy+xS0dng==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1jwlwsx5n7hu79qgpw86g6nuf35c6gauartjpehjgltwgv623aeasst9e8s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuSEtXWHZlUjJBSlpRbjJj
            VEZjVDgwV0RXMjQ1cWdzMzRBalVPaEFKN0hzClZWWW5QWnNEaVZRS3FKa2Fma0k4
            MUFCZE5oMHpkMkNsaHp1bGFLbnY3aVEKLS0tIEUyUDlXYWJwSGRha2dhUTFwYlNo
            WTVGOEJEK012MlI4R1ZBU21rdG5lTlEK8kSOcXTscZnm9nGMD8VQf4NdD69D6U6+
            Y4BWjFDowkI+3+JQbi6ARhjufk9yF7LbL28Yqfn+4ZAI3VoZxtfpCQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-13T23:21:49Z"
    mac: ENC[AES256_GCM,data:/lcV3whq40jBW5YCbfi6nxXFCrpUjQoFcxLgWZqY0X6G82nx9rrPTO2MjfbE2Jh5Z3/DXBSAMw5b8zp/2cBbRx+gJrCShwhDFyiOx/wv0EJsAu5iUUaFSKqz7QbPvYUej+XgZFFddieG5tWFYBUX4Tahh33BO5CHsezu32P0a0c=,iv:RAQ9bD1XrHKSPNjLnB9C+CWReHuFnR/wV4oRt7/Vttw=,tag:I6/uhlRnVr1KueDOMajLew==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
