apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:1gAMHlGlkp2gQ7BfBcT4hWkj9/sL0QD1sHbEnseqX6k/pzj2aXPxkkCB7Q6tLlmL06FcGhz3LqSlbEvP4fylgTFC1eomX7qf11fDjcenSjYDJz67b1IyXqTz6TuU5ZnGmxsrxPH2kwEPBuDlD2YbvHP6jUols4WDptgtswdX1ZZ9m+AL27XuvYNrJLrhxv1XDNAsUlPcBcKsYb2MrtQOXphWWQaJnYVWNFyoyoINFicCArSbAB8vKxHS2U4kBBGf/86SighL7fy3dH/YsWCpAbtMrN/n4iFxw3DNOWVus3uAjXeLARp7x5glqLxDxlirGDYvjOFlSjovt1gW6pVsSYzO2ckAWpqYOvAwJERhL5Z8i11u/VAZJJgDIoOW5HsP,iv:HdB1+uBBx8kvEkHhGsj9i4NfaTvu9+datCtmYFXigHI=,tag:iInio44anY+hKDl1RVdJsQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:NY0m+mkfR4HJWu+e/yS7jK7XxvAHikSAHuwYT7lmYcRszrZQAzHeenkFOT2HAyeEp5l+Oe9ly4CiH+5dJrjM+/PM0aT/K8TXnH94CIOpI4jHkucV51S1C9L3SkntVrENVucGMLR6GHUMrvSSoqt7/0cvNcbM8PRXkA3OJ5MvcGgSKhkea9uj9HHIbV4TiJ2YNUbd5QLnzztiP3Bo7Gdx0Z4iham7zI0HwF2ydBGdhgCSzkk/518lWhK7IJuR/V5TSC9FXRLnQ4Eb4gs8eQ==,iv:utkyXVTkMLS+j7nZTk/ixc5OxTyoc9MjqFb0rlM609E=,tag:k413OcrhUUxCsVya88PMXg==,type:str]
    known_hosts: ENC[AES256_GCM,data:FRPbmjYPfbvMQTvPnYf3yV28DusqWcMFcWN7QOv6IROzNOcHT0s5OWmjZyuL1iiVJHnQ3PndtlSyp5f0X5SQEOfoS+BKNAFi6mtPJh0bEJwXpaci48/0NZ1NUsK7xg6N3VUODhIf3A7ko/iRcesh7yM2plPeFjUcpoxmLMrinoOVIsu0/AFmomlVv2Hta+ycswnpzebBpLG87KYa//jgYDgc3UP4b/u8QwSk,iv:71Heao/8T415daaHnsc7ek3EEUxXM+3AEVml4eAU1P0=,tag:26cpElAswMMNCvI+a7Yjug==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1jwlwsx5n7hu79qgpw86g6nuf35c6gauartjpehjgltwgv623aeasst9e8s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqT0lsRlhhNWJOc25iaEZs
            akttOXloQUVkcURabTBSekJ0alJ5VXk0NzFBCk12ZmgrRysvaTlJQkRxbitTTStL
            Z0tZZTZ6a1FNVjlYVk5wdWE0Z2hyY0UKLS0tIHljSHUzMXhNbzFYcjBUMWtscmF6
            cW5JM3V1RzFvMEh5RWttSW9qOEhVMXcKGXPu0KvsyVKYllHHrabCestDTZOSPwkh
            hXZVMbwXwbkGjKpRboHLVzOZ41MQLugB0oHADHNRYQKfSbnhm4kW6g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-16T17:45:43Z"
    mac: ENC[AES256_GCM,data:tk90O/7P7nElgiZ+yLK3HMfjgAjC6UqnGRNW2Ij0+dtIw8hB5Sx5l8SsUaaHfaxU+ojeNn022xa+jkaSFfC0U1ifx27SZWWwoNJXM245fw6yP713Mo93Ac9BGBqjf9OnXDc3iQcrSZ+md0/p0S4gCkaXVjb6/2PJGD5+fKqH53U=,iv:hJmW5KdC/62DDlx1hxXFrqADKUGxJfSU6br2Lv72Zvg=,tag:6HGMM04owW/ngJSpyev/Bg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
