apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:ouXDmSr9odDyzxuAOtANRgzceGfrQMvgJEn0FQ4tI8PrNtdd192j+W4YT5/0VPvX15NS+acQXi6+cqrXGXqwfT+MCVge/PBthty/XOcXQcY5Ewz+cHJso0sJZHoydUDfubOZGpLm/s86N3CdJw9ZBISkK5DfzCZXhPSf2Hf3T6gaWDtyTfVGSYqweqnhpqKoVRP8A5W9eOVXVNlj14aSTv1L+YP/s/NzfI7msWSvsbd7c8xI0tCHhLyq4r7LevYGSHusL7gSFGSZe1zBhBIEoZubmo8F7/y1d0XWw0WA5dNvCOWbo8vcDe8/8P6lsrWk0Yn6Jt0sbsVkOVt48JjqYN3uwMXkJrtYnWHsoQzVB5B2B1rwFgTOT51xohcN7HKq,iv:ZVbZUFcdGzg98A/rmzbAcOzBMjUIZl6MldQuPjIX9BM=,tag:cSbl9zRSAZzOWFmhGEcrVQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:6eRVrkJMFAhPL482GDCG5nxqFedy0+6Xbjz8HqUAJGKXUJ7fGRwkmR8QVPAcADVhMNcLutM8vvfmpGGx/EjyItSPImTVhgglMZXhJsQv2qJCg0PUfDVVt5XHu7GOutMCep4kyD4BjnEEG3s89mpTRMNbKz50xXIo0p6pnvsftoDanD9nWU+LucGWdwAWZ65gYszj956Rlm4LH/zNid+Lhkt+3o+4OLjD0W3gn/pBKoZa5F1lhvrn2lQIY5zdXXbCWaaSFVzYqNp5tJCHng==,iv:K8KM7O01PLw3XvIUYBBPtiHshS669gpwx7SGlp1zn7g=,tag:rQvPwoz1RU6cE57Gn3Sq+w==,type:str]
    known_hosts: ENC[AES256_GCM,data:DQpomyF5WePCLUCIGpjPLJvJfttsNcVOdfzfIInQh6nOp8g1DpUPcQss4GYNDXGi3Y6rn3w/iNzupFJRP4h8MnKulnUdNcFRgEstxGG0wPiZCc15C9maM7tsrUZ4HRS3GvZNPybumT+gKlKZ0jkLdEcfF/BaKe95ZS/yx1yB99/OYZfBgveW/FsWuFp5yHvXefYcFbxXBwgHbsIj9mYs5+/RKyf47/55j2Wp,iv:KH4acoWJIl2QcFZcOJkfxlzp7LmsquWB/rw0kJInMeM=,tag:r3eAyXW3NajgVxEzjDggMA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1jwlwsx5n7hu79qgpw86g6nuf35c6gauartjpehjgltwgv623aeasst9e8s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwa3R6c2xqRHhWOER5Sk8x
            a3BkYlpSQXZ4M3grMjloaU1vUHRLRGlSZ1Y4CkxJTVJDZlVwelFCNmtmekxwaUhB
            VkxySCtvcDNZS29TazhZSm5iT3F1UEEKLS0tIFQ3ZElIWjJSaU1YMmIzZmg5T0tp
            STh1TllseCtHZlo1aVBUZVVDRnRzaTQKPKKt2TErfXBNZ/9WR2bkIyTN7/Rwxc+Y
            VkOySsExg3xuRHnbjRjkbcPUqNdWs4ta4QQyGYbxD3ruk7GnaeK4UQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-17T23:30:15Z"
    mac: ENC[AES256_GCM,data:vVoF9+PTuqB46B+vz7BuIo7A+LpNrz/SGRptSTKWepusj2DyrV6OK1ycwkucVWkcCDk3SggdkQ4vcGNVNFLDhzMfVITMqL6F8PmSu9yszuAovt0xvkC9uWxS9twAv8D5CgVwHywcPqDjFdKosqrMuqQK7rUytf2VX60dNRCvhRw=,iv:NagRC5G9vnhwzbljuNWpym0V/pxlXH7sSx72ucTdULw=,tag:kNk5suNuLeiGLJzpo3OBhg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
