apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:OUBxl9he0s5yEskdoRLU66LimtY2XEIDeSsEwuqAPwqq7Zf6nDA92Vv39NdAgVrViWb4yzwD+tgUBhRIMRaj5BUii77JBhQHk8t/Ll1GFFT4XPtxD7ONWCAjuqblNVi2LB01xS7WvXK6ETKJYguHRLCQBQPv5kk7D5x9BTv5biKoUQvOm3g3KCPWVtpGYcOJNEm4V6LF6NpTx+g3hWdQFubXJx5BCpje5x6+56IVvJsH26e+aElKFmifD2R+yMRT3AmEY4nGPgT6gRB1ZtCuWs/IYJ0DvdqU2rnRMV47SOy5nZMd569dh4wIbuY+sLdeaOgZJcnkXKDQslYf8OcxH4Phm0OR0Efd8bMvbO3mvXTXV8NUU8vwyvLbiOtkowo+,iv:r3OdDdGvTM8xlnGmRLET5XxympBonyvlHibJPcF/HKM=,tag:jv5bJizx8IlyIKeH03HOjQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:uUrGZPfguLKI4P7J8XSlO6SkB4IjVUx92nJCUUdgOxUCo4ffqiexlxteCQ5+2GcV6Tq+tOm35Yno1N7WIY1s1tiDwZpwu01Y8KacmOPH2M3lJ2KvXTflZs9rgv92vb3MMj18mJoTQ66aPlSQOmny1Xuju/OJbLP3DHoK3+iDlwmrmaHV7eC1BUpfMWQgbpL7CkT4JL5ug3lqi+7RIKqxM75arDsAzrpxtg8b8MQYo5Ks0a+UzJgfN/7X/wzCedoIUiUmMje2n3pqpomwZQ==,iv:wfL/qsicZ2qAj7Zo5paNlqzcymWPOzOIUhzNozWaLG8=,tag:A8RFZQVP2KGIs7v9FYtJ2A==,type:str]
    known_hosts: ENC[AES256_GCM,data:cOoQ3q3rDT7vtPn30NRkgwWwbJeHsys6iNpholY06ll9AfcodmWUDlzOg3muUXVEA1EGoBIw8pg/cUfQHimNwZ2wBHoJjffXTlzdV6qKH0tsXEvBMaHd1sSbTOGYT4yTpJFwRNcrr0g/+ncj+FNRbrm3Ua0q7rSLawOchnbTlleGDfhF0d8z30AgnMZOMWQWJs+mSHjUvgeBT0RwKmbpfcoLjWHxywkY+QDj,iv:AP00DpYXBUOz7S/pDdl4Ic1rUMTz3oBUw+Wn8Z/CuX4=,tag:e2JvWp1IC31i2W/soewGCQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1jwlwsx5n7hu79qgpw86g6nuf35c6gauartjpehjgltwgv623aeasst9e8s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSWEdEZ09hVVJDQWIrSVJK
            V0ZNU2J5N25TajRMdkVkUXptcEZtclVMbVVBCndGeUdsTXZTUnJGY3hwSHZ4UHM5
            bitLdWxwVmdIS3pvUThDN29tQk1LNGcKLS0tICtUMWRHQTFLZ0ZTalZLdTBoMGdn
            SlBJWjRMNzVmMWljY3JyTkEvSkw2QVkKrnf+2+8FiB/sXOdDdZgSOY4P1GxHksNF
            Y42xT7y+uDeuNsPTi7Y6Obtnt5ymjugyAS0P5RHUX7tJpnmoFf4pUg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-23T19:41:59Z"
    mac: ENC[AES256_GCM,data:d8d3wZbD5m6hj6IUDuXCj5Gbhw+nwzFDhNE3h9DBJ+/VU3lDpHF2TG6UcP/umLWAW8iqb3HodLLPUez/BVZtr0UBX0YIcC0P1tHKXtPTYJVaz/6wpB/need4Z3lvby90E1jFTicIlpzG76Qgmm5gOAvle4teQMcyCzFN56GoKNE=,iv:2CkOVA1XLafNyxOOVfV5CxIQ9YORcTVffUKd7x89Fp0=,tag:YQPXBRQ3z1BAmQIxDqPwyQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
