apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:TEwlwmWYdjDl5Ie6nZOetsrh5XZKew+Wyn2MIw6cQCSZ75x/FnjSIdJaGbb6kzLvTQVdEYEEafq6GYSglJ5255fhibM0d2adQQrJUQrcOTiLiulahg++TgGYt23MVzDEZlL9ABSnI/wwuJkuH/G7evroGObyoKYSMKnQdCrHbB3uV/BoWC1U2GrpqN97IuonjoCDBVb6j50PdGDNrfZwYKvFTcP+mf6ZkW4uQlZBW60rXDF1Ie/hDu7KiTYb7lm46c5JTFyl9APlMGGVKp1e1uW8nnReqn7ti0/rhmcLHRPmGy6gTx+iilP4eFN9xwLAr5Hy5/l19GLNudhRCqqYc63Zd4De6ruC8FukuLE5veWLB/yK/dHz6ht+4PN6jiCs,iv:La4eubK9HE1aBx1IpH5XhSFmIJNHGq/0PpLJtg6DzQE=,tag:JAHNR4sytdli6RD1oP0ppg==,type:str]
    identity.pub: ENC[AES256_GCM,data:1QgzzokVqiwPABdZkhQFOREqJaw+tqiEm7rc80XcLfYPY/37fUjLrodYtlQOVpMO6b6TxXnWzzYgiEJsNejKlWEr0EanUqcogjoUnAzde8ti8DtsWMSNyNCBYyUcY/G8kJL612w4G43UzF/9B50+w0e+4kQvG87PH+0OnNivNmZT5xOKsJ4RnyWwoSQDy/4ZJ2fTfZzZr3Q0P5taR3mI1IBs29ybF/DbgDHOVkSnEJLYTAglzXZRqY8tuJVOD7nbtN4Xl0dbneIM2e3fkw==,iv:WcLpH5ZaCq7kFkD+CDfcxmFZd+QSpnuJqTG8ED5lKxo=,tag:8IDLTFwtHneKmpcWiT3Skg==,type:str]
    known_hosts: ENC[AES256_GCM,data:iHXgDHQIA7vP30J1QOla7KNjei4ShVSAi5R6i+pn0z9nAQ4qdXQivIwv/Y7uhH8Dc+ye6HAFpz7/+2PknHikIBTpoqtGLRqj85YN1ByDdq2opZqMTAM5o2tNOni+Ib6b7vGWXwIGHtJRnfXdS9sZiyK2A8jciiT9wSLkkkyGedzNIgtwmJBLxFxCWzBUMN4mhAKbc2/xU6nKPqA2X7v6snOVVW6HN1Sdgoti,iv:06wwL1jUYmROZ1RTsF/DrsyR8Zt24PhhDwOICqT42II=,tag:7krl4j5r6pSoi3DvJ5ze6Q==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1jwlwsx5n7hu79qgpw86g6nuf35c6gauartjpehjgltwgv623aeasst9e8s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiYVFKU1YwaXZXR2FhYlpp
            MTR4MUlldmtFUlJhQXdMaFgwczJ0b252NkJ3Cit4M1dvdGhBSWNNYUEvN2trU2tS
            SE42elhMS2xBZkQ5SzFnU0tQNEtoYjgKLS0tIE81MjBsUXlJVjRON2k4dHZGMHl2
            ZTRxdVE3cGZPZEVad3hrb2FJU0F4bHMKvhGySfWY6GrjXxl82l+T80MtpYwsXsJM
            2xBdma5qFoKVWixwxeabxiejdEvkk13xgUdXf5ClUCv54hGgZGT8YQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-16T17:33:05Z"
    mac: ENC[AES256_GCM,data:yZt6qBNaBy0mGCmfh3oWlSj/PBolE0Of7e89zxJPunPuYXZtzglpK1e/oVp8gTvnwZ+Al1b9rSKDqPq2DblBKOvZpKOpRAcaMpNeGjQ4vV8dMyoqYerCbt/y6aWsxo2SYiLOphzMzRuhCyFsijkvqYNX3XQSzd9HDntzHtyq058=,iv:bQHnNuBEUJzYZS76CUtmgNLdOUddukOsyroF2suJQdg=,tag:+w7DZ3BfrCnQAzsuPbRdMA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
