apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:djg3wPJ3A4V4Us3HpEE+KUwvxN2VP/Fjjo9WcDUQYPQqgsoV8AcKg2W3UCpjgQBt1HrOUr5CLuDUWvOh3I8d8H+Qo7d49TH16vY89hVadVLLSUoHdoba8gt1QeDbU2b+ML3YgrCYpTKoMNJ7F2ju3VI2AELBW3iu16f6cZaWfrk20ax2hhv2HeJLkX0GdNfswY/OSoyXqRcpXh7Ot9AAwG/s4TmcICZJ9UDggFerCl6cO9PaMpVW9SHzZ2PxFEXvKFekv1GheDjyL7kapqhFHvfFnia/FPyCvc1rvoKvHjf98E189aUf6RwPqPLNrU3ElICklKlzkWRo7mPLDJ5pKZPEF6H32hACYG0jEXUu9V3zFGhZ+l4q4dXYC63YigkQ,iv:SavaQUkGcmVVRFdSdthMXNBfSMWwVvmvchcEJmAoyE4=,tag:yKi180SGp78NS5jbxVxaLA==,type:str]
    identity.pub: ENC[AES256_GCM,data:59fmhSw1DEUn38EhWiZpS69R3wpVm67Lzuy5lZZ0j2hYOXrc2yXkkEtbTKaShSDxPKWG7nIMOZ3dxGoyO0WVe1cfoTYmsXTDShB9E7ifJ3vAp7HxvJzBCX4KEpQCRJspWC6S+3hVvAE8FxmL34w2qYxJDbiVw0mW3Qh+yaNvusYTACOpIji9VEJwRM3DlQr+9QcURZfjysukeAaRr1cLKl9vsDmeVi4886h7sHsV1Po5WwAzkDcpZ+DqA5butv1O/kZRk7I3+KWYTgwajw==,iv:+c9A1kWguIDi4HKD3KZ4qQ+6LyiFx4GJPA1BLxrVDlc=,tag:+uNDmWAoJad32qS9b/cT4g==,type:str]
    known_hosts: ENC[AES256_GCM,data:3X0JYdsSxpZws6XAFxI53l2QmuIa8LiVIS7o5h9qS4Fa+aHRJfCcowgczaqfTwOPXV5ZSd5PphU92eop4th9F9+DyenmsLOtFMK0mW6WkfCu/E85Y9CqH2S5qvBRAodmS0xLKZRIdXFRtby9QqTu4/TwfDBcnKDp7anOjyfmd9g97i04lIb/kM/xyIBwHu7mddb7OyrRp/f0zmnAKiEI8q50nEjwII58vmXe,iv:tHRFquLd/xm97zRx/kvA2DaBfedSXMLCYO1K/NWQd2c=,tag:gGTxyoBowP38qJRTV3J2+w==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1jwlwsx5n7hu79qgpw86g6nuf35c6gauartjpehjgltwgv623aeasst9e8s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByL2pid1JlSG0wTk5uODdC
            ZG54RUptYzY1YVhKZmllMnp0UlF1eGpEQmtvClQ5V3BHR0V4NE13a2dkY1J2Nklp
            ZG5sdElGTHdSR2xra0F1RE1iOHF0d00KLS0tIFZ4VUhCMGRLYXRrU1orc0ZBUVRO
            TXJJNWhqWmhReDl4WnBOY2FlVGVPSlUK2PfyHrxV7Ia4LcAZYBn1nYLkBaElyk/5
            OBGKvqPlMJduy1jqR8Er81rRdx07TtwnbgNE7SukYYbKHTZQFtPGsQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-27T22:44:06Z"
    mac: ENC[AES256_GCM,data:dUNW2l5CNLzdtSqEqgPWRWngJ+DZN4xxONyyOLCG/adGkDitytolrcV+m5LkEfy2Vo6sHQQRtk2uA6c1QXyTppaLm6n9VtdPbj+kTlGz5++jNJoIJ7qs+5V6m2Y4iOuKfES5I2fECAXhR1al+HswY4CsHsajbvFzvuJO51BKAN8=,iv:Sjfl3d5Hn4OwfKBZ/DoHuZSgr/GV84PkWVgMnlT1eYI=,tag:NZ+DFulVelNrJwzOrlHzMQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
