apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:IRE41b3mjk28IGYHc5WmfahhwxvCJ1k66Yw+9uWVZDMVvAe9AcwssWN3/yFMwuAKrN6e1UfATUJEy5Jh5OYNw7ia9tELhxzJT8lsh+hVfd9KNeyqZZEbc6Gb4c4gRiYqYa74wdWwIU/RpCiKf0ZkkTL/13Nguxxa7a/TCdcpPn7HPF8sT5kq+F/bYzMHzpHeHVN2wPrLGiHts3UhIozDlYVf9mRcaPkE0+uqlT5wXSEXe30TUqzYYQ+v9sdqIlzwR8hAuf86A2jTT+bIbnVPYd6pKZeXHxJDtZAz1U4RR2ZZ5PLPiIn+2EXrgpQ8DM0yJE42kxpGBUe5TgrF7w+0GGZU6Wdzwl2ZgzeVjQv2q2gOwKGhfj8EcyrFsqFSWsRH,iv:WAmcGVwhcwd/Q+6OC7YhvKDEAkdWJajK8KWHQ1OKRKo=,tag:9njSvVOnv1PGRG969mnsuw==,type:str]
    identity.pub: ENC[AES256_GCM,data:vnIQ1X3maqVjKdL1Kxn5fuSKZrZzmCq8RFiEKr9vv4lXZwlAYafadZQ+mJhoMFkqAlJ21HpLGTtFS2oIWI7EkqKu8+v/daR3dm0QknXgh7tHe5lC0f2zan6KiPPYl7qq0mdEywix2GHAeKhXhwR2sWqL+GnCaIpdVhDOEvVtNev37ONrk8QqIlS3AGQHktBPRrzcjEmId3+RIh9S1EYdizYx8dTNQ0JNj3iE4no9CPclPRvzAjgLppiaFWHyks4XMwV3fACjFiQn++K9dw==,iv:gyV8pCsJq+fzS0RmsPt06+ajriUVRyfVkEPeXlUf93Q=,tag:VqarEn/QnRNMgmQcPHP4lA==,type:str]
    known_hosts: ENC[AES256_GCM,data:+leB2YCC2HPqviWD+PspRPFX+R8c6QIRRRNUH+EE1Hg0fax/xqGwPRgcIOAbwiZAKzZ4IH2WoUk/oUzNFidIoGwr08rqHZlkUoecD+m9qzqHxu11+9eFUAEAEfHGH9Ssd4U/hlU1eqpUqpNNE8pXkNqRLYdf4v6xYY86iV74tZo8PneUr87MbWI293snpIOSlNDDvHLDNsA6+0NjPa4acE0t733CfazK2DHb,iv:XfzeZDZo1J23caz2VJQc4o8nQB7s+y4LpQ0IyiI/YBs=,tag:NwcFjdYKaEgvuSNp55Hm7A==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1jwlwsx5n7hu79qgpw86g6nuf35c6gauartjpehjgltwgv623aeasst9e8s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZSzZRUmh1KytsYURWT1Ur
            Z0tFYTdzRnMzVXZIUFpvN2JPV0U1NEs2V2lJClJCNHdHTkd0a01kUnB4Y1VWcy9Y
            ek5QTzhGSjRQbUN3STRoeEd3SkVjWkEKLS0tIENuQzFBTDJhTWVmUEdiSmk3cnZx
            dlo1WFIwVnpXRVRBU2dTY2lNZU5Nc00KUjIpN1gtumQSQOhtrmxK03gS3CNzAwFj
            7Tu6Lazq943aEnH/3VnDJ7tvUZANr5n0Ya1SKVcV+kwhngmvnAqRtw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-05T02:19:58Z"
    mac: ENC[AES256_GCM,data:2/tjLHlI6t98TOHpnEv0YNpRvkmu8e/d9RK7tMmz+PepR8MjtxjO0ekWX+bcdBizW4IJKoIHCyJ2e89Ja2NwF1FKGWx1rOBHHufPVHx14EsHB0chi4WTQu1fUnHCWl0llECBIFIKw5ee1KzW3vKuNC5adxurcgKcojWlUtMFKN4=,iv:9toBSrb/b5ZWdACBNwrULnG1DGHpa8uXFSiC0vTxMKo=,tag:PskFcqzSeZjUNmLcHvem+w==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
