apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:JJlBSzI0zYntrJRl/MTNqVG+BL6DytU4z++kdDK4KHGkh4m6pDSDDp+gUaFN5jgMRmXmA2dg77udSMdApAIyfAUegibMW/uCJQGtEFaksaY4x1lU3/rO/WikdkkAwmoWwNPylZLSh5ABbaYYRrRvZQNx2R2gYF0Edy/pKSAM1buxZgNx9lZyCIu1dgehX+PSejjA+vd6bROJCCRyRA181UoCpb7PYzwWZvBRiFfvKuLKtvTu4Xu/7n/I3c8OHOM0Igc7jH4U1bYLF2wun8O42oSA566rEQ+unh2RlUADSk2Q0N8fJ64YTVH7kXuuQMrN0WSULiJYa5tlZxDDbbnSbso4MGQWOzYLCjNgNr/b66/4HodmtD6il4T63Xc/hm1f,iv:/CmGbY0+0nUbTr8h4A4N4VJkUaNFVSA5+XtNl36hPDs=,tag:HrowJJJhZE3acZ1fq2U5Kg==,type:str]
    identity.pub: ENC[AES256_GCM,data:g7d0gXPXgSkDrvzdtNHJywSbIxbYesAqvec5kvN5FNMZk8YZbRBkLhyNbe1J8Yqw4JJOxGeDqvsW6mVYnMDt/jkZq1mXb1GUPpZjd7WwTwLDuoAGLaZbqAZCcVBAAxnB3fZ9kI/L2lmr/jpxFl8lvieuM9H765Ohw/D2lJaunOkvPUFUWPRdpHivweA39sABudX+inhXsHX6TQkRwGrDyL0mkCM0MMMNedGWDSUH94SYiUIvkxOEWPTgFh0V9UR9ad1yaWl1E+dnIR4n9Q==,iv:fOEY9Jelzwc4m3oZpnbUR0+lhUkkkwpO8Vdv5x/abWM=,tag:YQ5nIPvCr5c1yq8nCL2mkQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:ixuVXOZfczweuZDEbCUlAe6EU386Oe98dNc+3p34a1Rx3mm17dPHVC1vnWxutLNFyLdx9NsmMwWMOO/Utr7NwcL8ASE+919I1D/6OqqyRFIJb/puEhl3KcORyIYIyzDrgd+8tUyYukDMRjqXrYlm1MQqfwum0skBizBowSZPqje82MEkRnsCZCB3CRcInOdE99PbDv9HNNGx++rJdooQzVKvqMuEQSrP0TI2,iv:Gw9AGWH/7CTwCp02olvoWSAgReR8gZnsPq+e4Gn3pDA=,tag:wQuN4gek3m2W0o9hRw1nLA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1jwlwsx5n7hu79qgpw86g6nuf35c6gauartjpehjgltwgv623aeasst9e8s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwQ3dJV1c3TitsdTRid2pT
            MTRlWlVwdjVWNEU2RE1RL20xNytJcDE3UUg4CjFjRUdNWEN3bytrUjY3MHAzQ3RL
            UEk4clJVVHNMTk5qRUh1QmNZaThUQUkKLS0tIGNMUnFpZG1WTVFMb0M4NE5md1hz
            Sk0vd2l1Zk8xSkhtWnJsNlN3TEJCWlUK5joYnno5f1Oq7kQw0O0Z5lTB7t8QCKga
            0OQWNNagaQe01VvB6jrwVvH0LHgOEdnkQdI+rbP53pstlQF3JzhQlQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-17T22:41:01Z"
    mac: ENC[AES256_GCM,data:8P02re2GZys9YpgBnfM1/6pFceCk92P1ceuKLvGL3qj810aLi4YL65E75VQbRCbCMMBSknPTnZZ5wVFZL11SNE32p3I1864mae3iN77VtOYMl7NqECTeuNT2tzB8gtnaXPDeHNWRcZqFHimtaCWg981oXQ5Wp/a7Jz2q67kyFJg=,iv:t8PeRfhSySah2N/FEQa7JEQUqcC4J1Et24RFvDdvNLM=,tag:aqhYcnqTxlbGaqn6A1Gl5w==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
