apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:uiNX9QU6I1bIaL3+HhE06CfpHAQBwu07xQrIYFaK1cbf0MqgE0B4ZPunGN9cvGo/WDgChEj8oDasFJe8RYm/YU68n5hWnQt0gCjRtWSs4WG1oqXr4fwdn12qmIZ0OwacbTwYz6WpyK9qh6EBaqaxqQxs7qxb6EvSEkNudR+R6urF6Sq81H0biIM666WPKzJdgTdOuu9nSvAw5hgZhfDcSXGWgTOzi9VW1iA5OaLunIhbGQ5qzufQLi1ic7NiWBKFRIw1vBDzevoIi9PNeAyifkULtX2tvHwzphB+ZjPSs3VvJdoFHErcbOfbczwvdr7x4pN/rhG6cz+87DSz17H3X3jvIfQm7qiDDGuFwsMYa2jadPWkFtGuf8/9sWLFuPNk,iv:oBpNlmCqKJGZJRT9MUACnL2TmvmEoRalwiAheHar1bA=,tag:zA98XHaEHxEpGys9/0cBBw==,type:str]
    identity.pub: ENC[AES256_GCM,data:fDO0YQQ60i8x2yh8hFjUsnL9Ws2B3a1dKW5vo8bcv9NAwdfiMiYWMqr/S8+Ep3DSJBSGdxSekiQ+7GxjpKAGL6chzIrzSiECyCKN3+KlCUBpbJJk8j7IGcAgEKllWssyvpAFMZT+yDSexBJUFKz/4dqgEe0geMdT915tGd29h3Fai0mgmwPoQlQhkmaeusQ4XNESud2r6rypNtqvZQZ77uqFvagC3ei/uQNgzLKY/azQU1keDGMTPbwB36lggyyFViPfD1Pq7Lltjf1WQw==,iv:M4ZfauevSd7KW9vSWB5eTKo/+ff+Zu0o6NNY1AMj3BY=,tag:7MgJ30Z/burJimivxOjM+Q==,type:str]
    known_hosts: ENC[AES256_GCM,data:6J0v2+PEjfGLRbwbnGKMrqu3RjaiQZnjNitgB+9lsFkpF+m73dQmw+Cr/3Clfv7KvUNIXqjFwZvGbCeEeUKiDQfz3o/actQ1pObyoIFLwJuf56XJ0C5ItQxn5iBG7aUvm4O2wQQU6Ns/P30AMKcoZdrt90bPfE2YkkSjcWexK9rv/dhUxQ5o13jTYXICfGBb/c7U9wD7N5ElYq9xzmqDgy4ujr3SkIlVsu/E,iv:P+pBM8cnKmbeo9uUwjlY49ewRxqUnPCI86X/AOT6Dqs=,tag:4CkZsW4/sNHwxi57x5uQvw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1jwlwsx5n7hu79qgpw86g6nuf35c6gauartjpehjgltwgv623aeasst9e8s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzbEVwOWlvNmZvY0s1RTBu
            TlIvbnl0THVFLy9KS1czNVY2dFZvR0Y0dVUwCmFnTXRpQXBGa3o1Z3Y0Y1JOZnFt
            T2kyZnFBZCs3TnlNNXVvRDkxRXkrTk0KLS0tIHZlUlp4MnFZSm00MWVyK01aaVgw
            a1A1YjRlQ2hVaWJWREYxZkdLM0Q0M0EKemH38FgBqrxvEMEtUwdOR75GeuIyNTpd
            SlPw15tF/1H7L+VZumLVXct0hE32nvfCUFFIxPTlqSaaAZ/70KKdBA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-17T03:06:10Z"
    mac: ENC[AES256_GCM,data:ZwC875J2ydeDDXjqtQKFfBpRLhKCuTiOvdEkS81OgYEpzmCyHLyEOCtaeEfFShZ6qfisOR3xRoTRsGOwRCOlB/xQ7VKvpyoyfpAWdeRTFOokkWMo0FKUZ5Ii73T8/f0h62qyu0f3Ys+GT1HFKF7If05UfXCTLaKGCIyLhKeXjxY=,iv:2PORt0MF3ZeoEb+bkHXR+RFeq9IPfrdbCaGQ+UXMP40=,tag:B0+6cwMlMd+CHaYyZlkP+Q==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
