apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:S76VWpmW0D6x17v09OVG8GcsdLvJ/hk750lRKUP3Lj1H4BSeNzU5hL30XZVDhSMbg96Fw/S+b9Y4jPUQVDCQbzXx8RQXttXjVhRBhsA9NL2aqb7u1V68fJhgGc2z8F9iV2pQ8kLDqLxlOfunOdfoRkykRh54k+KLhS6Ppkx2ZsTibB2sJ1VwndGwplW3yATdbeGr7jJjAC8+IZHNdXXbHfsjSs4/om89bT2Rh1m7s61dTz2DiaOy4HQGIJLoGq9XrZoBYUY+JlyH2RoIYb3x7ENhpmHQS9UXCPKh4rQtl3vY6yOlGrjJK2aEvhpAmOrBMhBVFIBkMIIya2F3I8VS62YeIM1l0DJ8HiFpNd/cx7ItP7dk4OczHDnsz0BRPTDx,iv:tgjhA2lCOEEFAHGVkLgMz+8VEfGwJSTj7EF6w65JnP0=,tag:HTxfhZrl/XB+PUuCsL1Y2w==,type:str]
    identity.pub: ENC[AES256_GCM,data:fYXHr1QNdOvPa34/DPbMdcdAeeZ32TUP/ZX9J14SJyHZ98gIgUrH4u4nhj+Dgj++N+KmX9HxO7TOcP0oo3LPS6gQg00SIPIZSg7wNKaubc/8PH48IJafVyRvzRg8MW+NEYppvijQc1+XG1glkELbJCwbSA0g+N3KJ1LxNr+9/B+CrPegc0LrzdXO/Rdpkjg2O6he/lpz2VkCW31GhexSWuWJs7LN/4nu9bOwVPQqlfdVbsPJCxyv4GP5WzDRPLCrkCVTjxZbvwh/esdCAA==,iv:kZJqBtZCff2r6XC3YmPgRsBClh/6WmyzFrQO/fCOvxo=,tag:/1uniVcyBpDASgE1O7Y7nw==,type:str]
    known_hosts: ENC[AES256_GCM,data:WkZg19YzKUXfqnOwT4RUpxawxFEwIYDPorodm7YmNXYAFHdYtLruNeX8MVLZtNTWJaAKcJx462QGqvujXPCCUwZ+Cq0lHYAYSPFZ/7RxzDjU8q0tfJ34sTGAiTM1b2luR0qPdH/1jjG07KIFwGF8J0QHOUgcY6mxDAXq5S8nj5DhY4LwTrsdyfLzd9XzZyQptGhEcBd7t/G0EXeTNalbdbtRxhQ+72sg5DdC,iv:hWJO4q6KtCokfiPiVXLxynzEkICMzjU+g+sAoP1Ssh4=,tag:4JUrmlAccUO3N0nd4+/R9A==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1jwlwsx5n7hu79qgpw86g6nuf35c6gauartjpehjgltwgv623aeasst9e8s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJOFYxSkRYeEQ1TUJXTHJr
            RlAySjhYbkhFYldGQmZsV21VOTdxSXlWc0Q4CncxdytpMDJFbEwzTVkyREZZWTUx
            b3lnM040N0ptN0VhRzZqYUVwQTZlVTAKLS0tIEIwNDg3OWZTaGEreWNBNHJSTmJw
            MFk3U3l4cHN4dXdPN1czSHczYkpjYm8K9EugNuHqQ+lDQbWGe8aT4bsD614fayQm
            iRtGDS4wRYSlDeg0eMO55q2bLjCzdAJ4PKAUsj6xqRLt1yDA/aTOmw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-29T03:17:20Z"
    mac: ENC[AES256_GCM,data:sXHbqhKeibY7IScmw89yLpSRfNsWmrCLxLDXzaP3Qt/LSmfxNUgJ5dpEzbe9mg35KjrA2NC2D9t9k722FMRX8N0Z5uFOGO7LE5jfUJZFFXD7Lgb34LoAyuUegoiPCDdGlwTXi0imdn4URXXkta9uL93xskjajnNQY+Dh2J09dgs=,iv:vskPzv+JRB3cyvvHfHlWWdy5mcUIXodSjZszp1b+I9s=,tag:01AVbcNT3oIP1jIXnZV/FA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
