---
# yaml-language-server: schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: xteve
  namespace: xteve
spec:
  interval: 15m
  chart:
    spec:
      chart: xteve
      version: 15.5.1
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false

  values:
    TZ: America/Chicago
    global:
      stopAll: false
    credentials:
      s3:
        type: s3
        url: "${MINIO_S3URL}"
        bucket: "${MINIO_S3PREFIX}-xteve"
        accessKey: "${MINIO_S3ID}"
        secretKey: "${MINIO_S3KEY}"
        encrKey: "${MINIO_S3KEY}"
    service:
      main:
        type: LoadBalancer
        loadBalancerIP: ${XTEVE_IP}
        ports:
          main:
            port: 34400
            targetPort: 34400
    ingress:
      main:
        enabled: true
        ingressClassName: external 
        hosts:
          - host: xteve.${DOMAIN_1}
        integrations:
          traefik:
            enabled: false
          certManager:
            enabled: true
            certificateIssuer: domain-0-le-prod 
    persistence:
      config:
        size: 1Gi
        volsync:
          - name: config
            type: restic
            credentials: s3
            src:
              volumeSnapshotClassName: csi-ceph-blockpool 
              enabled: true
              schedule: "0 16 * * *"  
            dest:
              volumeSnapshotClassName: csi-ceph-blockpool 
              enabled: true
