---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ext-plex
  namespace: ext-plex
spec:
  interval: 15m
  chart:
    spec:
      chart: external-service
      version: 16.1.0
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  driftDetection:
    mode: warn
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    TZ: America/Chicago

    service:
      main:
        type: ExternalIP
        externalIP: ${PLEX_IP}
        ports:
          main:
            protocol: http
            port: 32400
    ingress:
      main:
        enabled: true
        ingressClassName: internal
        hosts:
          - host: plex.${DOMAIN_1}
        integrations:
          traefik:
            enabled: false
          certManager:
            enabled: true
            certificateIssuer: domain-0-le-prod