---
# yaml-language-server: schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rustdesk
  namespace: rustdesk
spec:
  interval: 15m
  chart:
    spec:
      chart: rustdesk
      version: 1.3.2
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false

  values:
    global:
      stopAll: false
    credentials:
      s3:
        type: s3
        url: "${MINIO_S3URL}"
        bucket: "${MINIO_S3PREFIX}-rustdesk"
        accessKey: "${MINIO_S3ID}"
        secretKey: "${MINIO_S3KEY}"
        encrKey: "${MINIO_S3KEY}"
    TZ: America/Chicago
    ingress:
      main:
        enabled: true
        ingressClassName: external
        hosts:
          - host: desk.${DOMAIN_1}
        integrations:
          traefik:
            enabled: false
          certManager:
            enabled: true
            certificateIssuer: domain-0-le-prod         
    persistence:
      data:
        storageClass: ceph-filesystem
        size: 10Gi
        accessModes:
          - ReadWriteMany        
        volsync:
        - name: data
          type: restic
          credentials: s3
          dest:
            volumeSnapshotClassName: ceph-filesystem
            enabled: true
          src:
            volumeSnapshotClassName: ceph-filesystem 
            enabled: true
            trigger:
              schedule: "0 15 * * *"        
